/**
 * Offline WWOB generator. Reads hand-authored show data, runs the (framework-free)
 * `src/wwob` machine, and writes:
 *   - one export-grade SVG per show  →  public/shows/<id>.svg
 *   - a typed manifest the app reads →  src/data/shows.generated.ts
 *
 * Run with `npm run generate`. Re-run whenever you add or edit a show.
 */
import { mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  buildStripes,
  parseDuration,
  svgMarkup,
  totalWidth,
} from '../src/wwob/index.ts';
import type { ManifestEntry, Show, ShowFile, Song } from '../src/wwob/index.ts';

/** Uniform export height; the SVG scales, so this is just the canonical unit. */
const HEIGHT = 100;

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const dataDir = join(root, 'data', 'shows');
const svgOutDir = join(root, 'public', 'shows');
const manifestOut = join(root, 'src', 'data', 'shows.generated.ts');

function parseShow(file: ShowFile, source: string): Show {
  if (!file.id || !Array.isArray(file.songs) || file.songs.length === 0) {
    throw new Error(`${source}: missing id or songs`);
  }
  const songs: Song[] = file.songs.map((s, i) => {
    if (!s.title || !s.duration) {
      throw new Error(`${source}: song ${i + 1} missing title or duration`);
    }
    return { title: s.title, durationSeconds: parseDuration(s.duration) };
  });
  return { ...file, songs };
}

function toManifestEntry(show: Show, songCount: number): ManifestEntry {
  return {
    id: show.id,
    date: show.date,
    venue: show.venue,
    city: show.city,
    state: show.state,
    country: show.country,
    tour: show.tour,
    collection: show.collection,
    tags: show.tags,
    svg: `/shows/${show.id}.svg`,
    songCount,
    songs: show.songs,
  };
}

function main(): void {
  const files = readdirSync(dataDir)
    .filter((f) => f.endsWith('.json'))
    .sort();
  if (files.length === 0) throw new Error(`No show data in ${dataDir}`);

  mkdirSync(svgOutDir, { recursive: true });
  const manifest: ManifestEntry[] = [];

  for (const file of files) {
    const raw = JSON.parse(
      readFileSync(join(dataDir, file), 'utf8'),
    ) as ShowFile;
    const show = parseShow(raw, file);
    const stripes = buildStripes(show.songs);
    writeFileSync(
      join(svgOutDir, `${show.id}.svg`),
      svgMarkup(stripes, HEIGHT) + '\n',
    );
    manifest.push(toManifestEntry(show, show.songs.length));
    console.log(
      `✓ ${show.id} — ${show.songs.length} songs, ${totalWidth(stripes)}px wide`,
    );
  }

  manifest.sort((a, b) => a.date.localeCompare(b.date));
  const banner =
    '// GENERATED by `npm run generate` from data/shows/*.json — do not edit by hand.\n';
  const body = `import type { ManifestEntry } from '@/wwob';\n\nexport const shows: ManifestEntry[] = ${JSON.stringify(
    manifest,
    null,
    2,
  )};\n`;
  mkdirSync(dirname(manifestOut), { recursive: true });
  writeFileSync(manifestOut, banner + body);
  console.log(
    `✓ manifest → src/data/shows.generated.ts (${manifest.length} shows)`,
  );
}

main();
