// GENERATED by `npm run generate` from data/shows/**/*.json — do not edit by hand.
import type { ShowSummary } from '@/wwob';

export const shows: ShowSummary[] = [
  {
    "id": "1969-02-27",
    "date": "1969-02-27",
    "venue": "Fillmore West",
    "city": "San Francisco",
    "state": "CA",
    "country": "USA",
    "tour": "1969",
    "collection": "Fillmore West 1969",
    "tags": [
      "1969",
      "Dark Star",
      "Live/Dead"
    ],
    "svg": "/shows/1969-02-27.svg",
    "songCount": 10
  },
  {
    "id": "1969-02-28",
    "date": "1969-02-28",
    "venue": "Fillmore West",
    "city": "San Francisco",
    "state": "CA",
    "country": "USA",
    "tour": "1969",
    "collection": "Fillmore West 1969",
    "tags": [
      "1969",
      "Dark Star",
      "Live/Dead"
    ],
    "svg": "/shows/1969-02-28.svg",
    "songCount": 16
  },
  {
    "id": "1969-03-01",
    "date": "1969-03-01",
    "venue": "Fillmore West",
    "city": "San Francisco",
    "state": "CA",
    "country": "USA",
    "tour": "1969",
    "collection": "Fillmore West 1969",
    "tags": [
      "1969",
      "Dark Star",
      "Live/Dead"
    ],
    "svg": "/shows/1969-03-01.svg",
    "songCount": 11
  },
  {
    "id": "1969-03-02",
    "date": "1969-03-02",
    "venue": "Fillmore West",
    "city": "San Francisco",
    "state": "CA",
    "country": "USA",
    "tour": "1969",
    "collection": "Fillmore West 1969",
    "tags": [
      "1969",
      "Dark Star",
      "Live/Dead"
    ],
    "svg": "/shows/1969-03-02.svg",
    "songCount": 14
  },
  {
    "id": "1972-04-07",
    "date": "1972-04-07",
    "venue": "Wembley Empire Pool",
    "city": "London",
    "country": "ENG",
    "tour": "Europe 1972",
    "collection": "Europe 72",
    "tags": [
      "1972"
    ],
    "svg": "/shows/1972-04-07.svg",
    "songCount": 25
  },
  {
    "id": "1972-04-08",
    "date": "1972-04-08",
    "venue": "Wembley Empire Pool",
    "city": "London",
    "country": "ENG",
    "tour": "Europe 1972",
    "collection": "Europe 72",
    "tags": [
      "1972"
    ],
    "svg": "/shows/1972-04-08.svg",
    "songCount": 22
  },
  {
    "id": "1972-04-11",
    "date": "1972-04-11",
    "venue": "City Hall",
    "city": "Newcastle",
    "country": "ENG",
    "tour": "Europe 1972",
    "collection": "Europe 72",
    "tags": [
      "1972"
    ],
    "svg": "/shows/1972-04-11.svg",
    "songCount": 27
  },
  {
    "id": "1972-04-14",
    "date": "1972-04-14",
    "venue": "Tivoli Concert Hall",
    "city": "Copenhagen",
    "country": "DNK",
    "tour": "Europe 1972",
    "collection": "Europe 72",
    "tags": [
      "1972"
    ],
    "svg": "/shows/1972-04-14.svg",
    "songCount": 29
  },
  {
    "id": "1972-04-16",
    "date": "1972-04-16",
    "venue": "Stakladen Cafeteria, Aarhus University",
    "city": "Aarhus",
    "country": "DNK",
    "tour": "Europe 1972",
    "collection": "Europe 72",
    "tags": [
      "1972"
    ],
    "svg": "/shows/1972-04-16.svg",
    "songCount": 29
  },
  {
    "id": "1972-04-17",
    "date": "1972-04-17",
    "venue": "Tivoli Concert Hall",
    "city": "Copenhagen",
    "country": "DNK",
    "tour": "Europe 1972",
    "collection": "Europe 72",
    "tags": [
      "1972"
    ],
    "svg": "/shows/1972-04-17.svg",
    "songCount": 23
  },
  {
    "id": "1972-04-21",
    "date": "1972-04-21",
    "venue": "Beat Club",
    "city": "Bremen",
    "country": "BRD",
    "tour": "Europe 1972",
    "collection": "Europe 72",
    "tags": [
      "1972"
    ],
    "svg": "/shows/1972-04-21.svg",
    "songCount": 10
  },
  {
    "id": "1972-04-24",
    "date": "1972-04-24",
    "venue": "Rheinhalle",
    "city": "Düsseldorf",
    "country": "BRD",
    "tour": "Europe 1972",
    "collection": "Europe 72",
    "tags": [
      "1972"
    ],
    "svg": "/shows/1972-04-24.svg",
    "songCount": 26
  },
  {
    "id": "1972-04-26",
    "date": "1972-04-26",
    "venue": "Jahrhundert Halle",
    "city": "Frankfurt",
    "country": "BRD",
    "tour": "Europe 1972",
    "collection": "Europe 72",
    "tags": [
      "1972"
    ],
    "svg": "/shows/1972-04-26.svg",
    "songCount": 30
  },
  {
    "id": "1972-04-29",
    "date": "1972-04-29",
    "venue": "Musikhalle",
    "city": "Hamburg",
    "country": "BRD",
    "tour": "Europe 1972",
    "collection": "Europe 72",
    "tags": [
      "1972"
    ],
    "svg": "/shows/1972-04-29.svg",
    "songCount": 22
  },
  {
    "id": "1972-05-03",
    "date": "1972-05-03",
    "venue": "Olympia Theatre",
    "city": "Paris",
    "country": "FRA",
    "tour": "Europe 1972",
    "collection": "Europe 72",
    "tags": [
      "1972"
    ],
    "svg": "/shows/1972-05-03.svg",
    "songCount": 32
  },
  {
    "id": "1972-05-04",
    "date": "1972-05-04",
    "venue": "Olympia Theatre",
    "city": "Paris",
    "country": "FRA",
    "tour": "Europe 1972",
    "collection": "Europe 72",
    "tags": [
      "1972"
    ],
    "svg": "/shows/1972-05-04.svg",
    "songCount": 29
  },
  {
    "id": "1972-05-07",
    "date": "1972-05-07",
    "venue": "Bickershaw Festival",
    "city": "Wigan",
    "country": "ENG",
    "tour": "Europe 1972",
    "collection": "Europe 72",
    "tags": [
      "1972"
    ],
    "svg": "/shows/1972-05-07.svg",
    "songCount": 27
  },
  {
    "id": "1972-05-10",
    "date": "1972-05-10",
    "venue": "Concertgebouw",
    "city": "Amsterdam",
    "country": "HOL",
    "tour": "Europe 1972",
    "collection": "Europe 72",
    "tags": [
      "1972"
    ],
    "svg": "/shows/1972-05-10.svg",
    "songCount": 32
  },
  {
    "id": "1972-05-11",
    "date": "1972-05-11",
    "venue": "Grote Zaal De Doelen",
    "city": "Rotterdam",
    "country": "HOL",
    "tour": "Europe 1972",
    "collection": "Europe 72",
    "tags": [
      "1972"
    ],
    "svg": "/shows/1972-05-11.svg",
    "songCount": 29
  },
  {
    "id": "1972-05-13",
    "date": "1972-05-13",
    "venue": "Lille Fairgrounds",
    "city": "Lille",
    "country": "FRA",
    "tour": "Europe 1972",
    "collection": "Europe 72",
    "tags": [
      "1972"
    ],
    "svg": "/shows/1972-05-13.svg",
    "songCount": 25
  },
  {
    "id": "1972-05-16",
    "date": "1972-05-16",
    "venue": "La Grande Salle Du Grand Theatre",
    "city": "Luxembourg",
    "country": "LUX",
    "tour": "Europe 1972",
    "collection": "Europe 72",
    "tags": [
      "1972"
    ],
    "svg": "/shows/1972-05-16.svg",
    "songCount": 22
  },
  {
    "id": "1972-05-18",
    "date": "1972-05-18",
    "venue": "Kongressaal",
    "city": "Munich",
    "country": "BRD",
    "tour": "Europe 1972",
    "collection": "Europe 72",
    "tags": [
      "1972"
    ],
    "svg": "/shows/1972-05-18.svg",
    "songCount": 25
  },
  {
    "id": "1972-05-23",
    "date": "1972-05-23",
    "venue": "Lyceum Theatre",
    "city": "London",
    "country": "ENG",
    "tour": "Europe 1972",
    "collection": "Europe 72",
    "tags": [
      "1972"
    ],
    "svg": "/shows/1972-05-23.svg",
    "songCount": 30
  },
  {
    "id": "1972-05-24",
    "date": "1972-05-24",
    "venue": "Lyceum Theatre",
    "city": "London",
    "country": "ENG",
    "tour": "Europe 1972",
    "collection": "Europe 72",
    "tags": [
      "1972"
    ],
    "svg": "/shows/1972-05-24.svg",
    "songCount": 26
  },
  {
    "id": "1972-05-25",
    "date": "1972-05-25",
    "venue": "Lyceum Theatre",
    "city": "London",
    "country": "ENG",
    "tour": "Europe 1972",
    "collection": "Europe 72",
    "tags": [
      "1972"
    ],
    "svg": "/shows/1972-05-25.svg",
    "songCount": 26
  },
  {
    "id": "1972-05-26",
    "date": "1972-05-26",
    "venue": "Lyceum Theatre",
    "city": "London",
    "country": "ENG",
    "tour": "Europe 1972",
    "collection": "Europe 72",
    "tags": [
      "1972"
    ],
    "svg": "/shows/1972-05-26.svg",
    "songCount": 31
  },
  {
    "id": "1972-08-27",
    "date": "1972-08-27",
    "venue": "Old Renaissance Faire Grounds",
    "city": "Veneta",
    "state": "OR",
    "country": "USA",
    "tour": "Summer 1972",
    "collection": "Sunshine Daydream",
    "tags": [
      "1972",
      "Sunshine Daydream",
      "Dark Star"
    ],
    "svg": "/shows/1972-08-27.svg",
    "songCount": 20
  },
  {
    "id": "1974-10-16",
    "date": "1974-10-16",
    "venue": "Winterland Arena",
    "city": "San Francisco",
    "state": "CA",
    "country": "USA",
    "tour": "Fall 1974",
    "collection": "Winterland 1974",
    "tags": [
      "1974",
      "Wall of Sound",
      "Winterland"
    ],
    "svg": "/shows/1974-10-16.svg",
    "songCount": 24
  },
  {
    "id": "1974-10-17",
    "date": "1974-10-17",
    "venue": "Winterland Arena",
    "city": "San Francisco",
    "state": "CA",
    "country": "USA",
    "tour": "Fall 1974",
    "collection": "Winterland 1974",
    "tags": [
      "1974",
      "Wall of Sound",
      "Winterland"
    ],
    "svg": "/shows/1974-10-17.svg",
    "songCount": 28
  },
  {
    "id": "1974-10-18",
    "date": "1974-10-18",
    "venue": "Winterland Arena",
    "city": "San Francisco",
    "state": "CA",
    "country": "USA",
    "tour": "Fall 1974",
    "collection": "Winterland 1974",
    "tags": [
      "1974",
      "Wall of Sound",
      "Winterland"
    ],
    "svg": "/shows/1974-10-18.svg",
    "songCount": 26
  },
  {
    "id": "1974-10-19",
    "date": "1974-10-19",
    "venue": "Winterland Arena",
    "city": "San Francisco",
    "state": "CA",
    "country": "USA",
    "tour": "Fall 1974",
    "collection": "Winterland 1974",
    "tags": [
      "1974",
      "Wall of Sound",
      "Winterland"
    ],
    "svg": "/shows/1974-10-19.svg",
    "songCount": 32
  },
  {
    "id": "1974-10-20",
    "date": "1974-10-20",
    "venue": "Winterland Arena",
    "city": "San Francisco",
    "state": "CA",
    "country": "USA",
    "tour": "Fall 1974",
    "collection": "Winterland 1974",
    "tags": [
      "1974",
      "Wall of Sound",
      "Winterland"
    ],
    "svg": "/shows/1974-10-20.svg",
    "songCount": 28
  },
  {
    "id": "1976-06-03",
    "date": "1976-06-03",
    "venue": "Paramount Theatre",
    "city": "Portland",
    "state": "OR",
    "country": "USA",
    "tour": "June 1976",
    "collection": "June 1976",
    "tags": [
      "1976"
    ],
    "svg": "/shows/1976-06-03.svg",
    "songCount": 24
  },
  {
    "id": "1976-06-04",
    "date": "1976-06-04",
    "venue": "Paramount Theatre",
    "city": "Portland",
    "state": "OR",
    "country": "USA",
    "tour": "June 1976",
    "collection": "June 1976",
    "tags": [
      "1976"
    ],
    "svg": "/shows/1976-06-04.svg",
    "songCount": 28
  },
  {
    "id": "1976-06-09",
    "date": "1976-06-09",
    "venue": "Boston Music Hall",
    "city": "Boston",
    "state": "MA",
    "country": "USA",
    "tour": "June 1976",
    "collection": "June 1976",
    "tags": [
      "1976"
    ],
    "svg": "/shows/1976-06-09.svg",
    "songCount": 23
  },
  {
    "id": "1976-06-10",
    "date": "1976-06-10",
    "venue": "Boston Music Hall",
    "city": "Boston",
    "state": "MA",
    "country": "USA",
    "tour": "June 1976",
    "collection": "June 1976",
    "tags": [
      "1976"
    ],
    "svg": "/shows/1976-06-10.svg",
    "songCount": 22
  },
  {
    "id": "1976-06-11",
    "date": "1976-06-11",
    "venue": "Boston Music Hall",
    "city": "Boston",
    "state": "MA",
    "country": "USA",
    "tour": "June 1976",
    "collection": "June 1976",
    "tags": [
      "1976"
    ],
    "svg": "/shows/1976-06-11.svg",
    "songCount": 24
  },
  {
    "id": "1976-06-12",
    "date": "1976-06-12",
    "venue": "Boston Music Hall",
    "city": "Boston",
    "state": "MA",
    "country": "USA",
    "tour": "June 1976",
    "collection": "June 1976",
    "tags": [
      "1976"
    ],
    "svg": "/shows/1976-06-12.svg",
    "songCount": 25
  },
  {
    "id": "1976-06-14",
    "date": "1976-06-14",
    "venue": "Beacon Theatre",
    "city": "New York",
    "state": "NY",
    "country": "USA",
    "tour": "June 1976",
    "collection": "June 1976",
    "tags": [
      "1976"
    ],
    "svg": "/shows/1976-06-14.svg",
    "songCount": 23
  },
  {
    "id": "1976-06-15",
    "date": "1976-06-15",
    "venue": "Beacon Theatre",
    "city": "New York",
    "state": "NY",
    "country": "USA",
    "tour": "June 1976",
    "collection": "June 1976",
    "tags": [
      "1976"
    ],
    "svg": "/shows/1976-06-15.svg",
    "songCount": 21
  },
  {
    "id": "1976-06-17",
    "date": "1976-06-17",
    "venue": "Capitol Theatre",
    "city": "Passaic",
    "state": "NJ",
    "country": "USA",
    "tour": "June 1976",
    "collection": "June 1976",
    "tags": [
      "1976"
    ],
    "svg": "/shows/1976-06-17.svg",
    "songCount": 24
  },
  {
    "id": "1976-06-18",
    "date": "1976-06-18",
    "venue": "Capitol Theatre",
    "city": "Passaic",
    "state": "NJ",
    "country": "USA",
    "tour": "June 1976",
    "collection": "June 1976",
    "tags": [
      "1976"
    ],
    "svg": "/shows/1976-06-18.svg",
    "songCount": 20
  },
  {
    "id": "1976-06-19",
    "date": "1976-06-19",
    "venue": "Capitol Theatre",
    "city": "Passaic",
    "state": "NJ",
    "country": "USA",
    "tour": "June 1976",
    "collection": "June 1976",
    "tags": [
      "1976"
    ],
    "svg": "/shows/1976-06-19.svg",
    "songCount": 20
  },
  {
    "id": "1976-06-21",
    "date": "1976-06-21",
    "venue": "Tower Theatre",
    "city": "Upper Darby",
    "state": "PA",
    "country": "USA",
    "tour": "June 1976",
    "collection": "June 1976",
    "tags": [
      "1976"
    ],
    "svg": "/shows/1976-06-21.svg",
    "songCount": 22
  },
  {
    "id": "1976-06-22",
    "date": "1976-06-22",
    "venue": "Tower Theatre",
    "city": "Upper Darby",
    "state": "PA",
    "country": "USA",
    "tour": "June 1976",
    "collection": "June 1976",
    "tags": [
      "1976"
    ],
    "svg": "/shows/1976-06-22.svg",
    "songCount": 21
  },
  {
    "id": "1976-06-23",
    "date": "1976-06-23",
    "venue": "Tower Theatre",
    "city": "Upper Darby",
    "state": "PA",
    "country": "USA",
    "tour": "June 1976",
    "collection": "June 1976",
    "tags": [
      "1976"
    ],
    "svg": "/shows/1976-06-23.svg",
    "songCount": 25
  },
  {
    "id": "1976-06-24",
    "date": "1976-06-24",
    "venue": "Tower Theatre",
    "city": "Upper Darby",
    "state": "PA",
    "country": "USA",
    "tour": "June 1976",
    "collection": "June 1976",
    "tags": [
      "1976"
    ],
    "svg": "/shows/1976-06-24.svg",
    "songCount": 18
  },
  {
    "id": "1976-06-26",
    "date": "1976-06-26",
    "venue": "Auditorium Theatre",
    "city": "Chicago",
    "state": "IL",
    "country": "USA",
    "tour": "June 1976",
    "collection": "June 1976",
    "tags": [
      "1976"
    ],
    "svg": "/shows/1976-06-26.svg",
    "songCount": 22
  },
  {
    "id": "1976-06-27",
    "date": "1976-06-27",
    "venue": "Auditorium Theatre",
    "city": "Chicago",
    "state": "IL",
    "country": "USA",
    "tour": "June 1976",
    "collection": "June 1976",
    "tags": [
      "1976"
    ],
    "svg": "/shows/1976-06-27.svg",
    "songCount": 20
  },
  {
    "id": "1976-06-28",
    "date": "1976-06-28",
    "venue": "Auditorium Theatre",
    "city": "Chicago",
    "state": "IL",
    "country": "USA",
    "tour": "June 1976",
    "collection": "June 1976",
    "tags": [
      "1976"
    ],
    "svg": "/shows/1976-06-28.svg",
    "songCount": 18
  },
  {
    "id": "1976-06-29",
    "date": "1976-06-29",
    "venue": "Auditorium Theatre",
    "city": "Chicago",
    "state": "IL",
    "country": "USA",
    "tour": "June 1976",
    "collection": "June 1976",
    "tags": [
      "1976"
    ],
    "svg": "/shows/1976-06-29.svg",
    "songCount": 22
  },
  {
    "id": "1977-04-22",
    "date": "1977-04-22",
    "venue": "Spectrum",
    "city": "Philadelphia",
    "state": "PA",
    "country": "USA",
    "tour": "Spring 1977",
    "collection": "Spring 1977",
    "tags": [
      "1977"
    ],
    "svg": "/shows/1977-04-22.svg",
    "songCount": 18
  },
  {
    "id": "1977-04-23",
    "date": "1977-04-23",
    "venue": "Springfield Civic Center Arena",
    "city": "Springfield",
    "state": "MA",
    "country": "USA",
    "tour": "Spring 1977",
    "collection": "Spring 1977",
    "tags": [
      "1977"
    ],
    "svg": "/shows/1977-04-23.svg",
    "songCount": 20
  },
  {
    "id": "1977-04-25",
    "date": "1977-04-25",
    "venue": "Capitol Theatre",
    "city": "Passaic",
    "state": "NJ",
    "country": "USA",
    "tour": "Spring 1977",
    "collection": "Spring 1977",
    "tags": [
      "1977"
    ],
    "svg": "/shows/1977-04-25.svg",
    "songCount": 21
  },
  {
    "id": "1977-04-26",
    "date": "1977-04-26",
    "venue": "Capitol Theatre",
    "city": "Passaic",
    "state": "NJ",
    "country": "USA",
    "tour": "Spring 1977",
    "collection": "Spring 1977",
    "tags": [
      "1977"
    ],
    "svg": "/shows/1977-04-26.svg",
    "songCount": 17
  },
  {
    "id": "1977-04-27",
    "date": "1977-04-27",
    "venue": "Capitol Theatre",
    "city": "Passaic",
    "state": "NJ",
    "country": "USA",
    "tour": "Spring 1977",
    "collection": "Spring 1977",
    "tags": [
      "1977"
    ],
    "svg": "/shows/1977-04-27.svg",
    "songCount": 18
  },
  {
    "id": "1977-04-29",
    "date": "1977-04-29",
    "venue": "The Palladium",
    "city": "New York",
    "state": "NY",
    "country": "USA",
    "tour": "Spring 1977",
    "collection": "Spring 1977",
    "tags": [
      "1977"
    ],
    "svg": "/shows/1977-04-29.svg",
    "songCount": 23
  },
  {
    "id": "1977-04-30",
    "date": "1977-04-30",
    "venue": "The Palladium",
    "city": "New York",
    "state": "NY",
    "country": "USA",
    "tour": "Spring 1977",
    "collection": "Spring 1977",
    "tags": [
      "1977"
    ],
    "svg": "/shows/1977-04-30.svg",
    "songCount": 21
  },
  {
    "id": "1977-05-01",
    "date": "1977-05-01",
    "venue": "The Palladium",
    "city": "New York",
    "state": "NY",
    "country": "USA",
    "tour": "Spring 1977",
    "collection": "Spring 1977",
    "tags": [
      "1977"
    ],
    "svg": "/shows/1977-05-01.svg",
    "songCount": 21
  },
  {
    "id": "1977-05-03",
    "date": "1977-05-03",
    "venue": "The Palladium",
    "city": "New York",
    "state": "NY",
    "country": "USA",
    "tour": "Spring 1977",
    "collection": "Spring 1977",
    "tags": [
      "1977"
    ],
    "svg": "/shows/1977-05-03.svg",
    "songCount": 24
  },
  {
    "id": "1977-05-04",
    "date": "1977-05-04",
    "venue": "The Palladium",
    "city": "New York",
    "state": "NY",
    "country": "USA",
    "tour": "Spring 1977",
    "collection": "Spring 1977",
    "tags": [
      "1977"
    ],
    "svg": "/shows/1977-05-04.svg",
    "songCount": 17
  },
  {
    "id": "1977-05-05",
    "date": "1977-05-05",
    "venue": "Veterans Memorial Coliseum",
    "city": "New Haven",
    "state": "CT",
    "country": "USA",
    "tour": "Spring 1977",
    "collection": "Spring 1977",
    "tags": [
      "1977"
    ],
    "svg": "/shows/1977-05-05.svg",
    "songCount": 19
  },
  {
    "id": "1977-05-07",
    "date": "1977-05-07",
    "venue": "Boston Garden",
    "city": "Boston",
    "state": "MA",
    "country": "USA",
    "tour": "Spring 1977",
    "collection": "Spring 1977",
    "tags": [
      "1977",
      "Boston"
    ],
    "svg": "/shows/1977-05-07.svg",
    "songCount": 20
  },
  {
    "id": "1977-05-08",
    "date": "1977-05-08",
    "venue": "Barton Hall, Cornell University",
    "city": "Ithaca",
    "state": "NY",
    "country": "USA",
    "tour": "Spring 1977",
    "collection": "Spring 1977",
    "tags": [
      "1977",
      "Cornell",
      "Barton Hall"
    ],
    "svg": "/shows/1977-05-08.svg",
    "songCount": 20
  },
  {
    "id": "1977-05-09",
    "date": "1977-05-09",
    "venue": "War Memorial Auditorium",
    "city": "Buffalo",
    "state": "NY",
    "country": "USA",
    "tour": "Spring 1977",
    "collection": "Spring 1977",
    "tags": [
      "1977",
      "Buffalo"
    ],
    "svg": "/shows/1977-05-09.svg",
    "songCount": 21
  },
  {
    "id": "1977-05-11",
    "date": "1977-05-11",
    "venue": "St. Paul Civic Center Arena",
    "city": "St. Paul",
    "state": "MN",
    "country": "USA",
    "tour": "Spring 1977",
    "collection": "Spring 1977",
    "tags": [
      "1977"
    ],
    "svg": "/shows/1977-05-11.svg",
    "songCount": 24
  },
  {
    "id": "1977-05-12",
    "date": "1977-05-12",
    "venue": "Auditorium Theatre",
    "city": "Chicago",
    "state": "IL",
    "country": "USA",
    "tour": "Spring 1977",
    "collection": "Spring 1977",
    "tags": [
      "1977"
    ],
    "svg": "/shows/1977-05-12.svg",
    "songCount": 21
  },
  {
    "id": "1977-05-13",
    "date": "1977-05-13",
    "venue": "Auditorium Theatre",
    "city": "Chicago",
    "state": "IL",
    "country": "USA",
    "tour": "Spring 1977",
    "collection": "Spring 1977",
    "tags": [
      "1977"
    ],
    "svg": "/shows/1977-05-13.svg",
    "songCount": 20
  },
  {
    "id": "1977-05-15",
    "date": "1977-05-15",
    "venue": "St. Louis Arena",
    "city": "St. Louis",
    "state": "MO",
    "country": "USA",
    "tour": "Spring 1977",
    "collection": "Spring 1977",
    "tags": [
      "1977"
    ],
    "svg": "/shows/1977-05-15.svg",
    "songCount": 21
  },
  {
    "id": "1977-05-17",
    "date": "1977-05-17",
    "venue": "University of Alabama, Memorial Coliseum",
    "city": "Tuscaloosa",
    "state": "AL",
    "country": "USA",
    "tour": "Spring 1977",
    "collection": "Spring 1977",
    "tags": [
      "1977"
    ],
    "svg": "/shows/1977-05-17.svg",
    "songCount": 25
  },
  {
    "id": "1977-05-18",
    "date": "1977-05-18",
    "venue": "Fox Theatre",
    "city": "Atlanta",
    "state": "GA",
    "country": "USA",
    "tour": "Spring 1977",
    "collection": "Spring 1977",
    "tags": [
      "1977"
    ],
    "svg": "/shows/1977-05-18.svg",
    "songCount": 19
  },
  {
    "id": "1977-05-19",
    "date": "1977-05-19",
    "venue": "Fox Theatre",
    "city": "Atlanta",
    "state": "GA",
    "country": "USA",
    "tour": "Spring 1977",
    "collection": "Spring 1977",
    "tags": [
      "1977"
    ],
    "svg": "/shows/1977-05-19.svg",
    "songCount": 19
  },
  {
    "id": "1977-05-21",
    "date": "1977-05-21",
    "venue": "Lakeland Civic Center Arena",
    "city": "Lakeland",
    "state": "FL",
    "country": "USA",
    "tour": "Spring 1977",
    "collection": "Spring 1977",
    "tags": [
      "1977"
    ],
    "svg": "/shows/1977-05-21.svg",
    "songCount": 24
  },
  {
    "id": "1977-05-22",
    "date": "1977-05-22",
    "venue": "Sportatorium",
    "city": "Pembroke Pines",
    "state": "FL",
    "country": "USA",
    "tour": "Spring 1977",
    "collection": "Spring 1977",
    "tags": [
      "1977"
    ],
    "svg": "/shows/1977-05-22.svg",
    "songCount": 24
  },
  {
    "id": "1977-05-25",
    "date": "1977-05-25",
    "venue": "The Mosque",
    "city": "Richmond",
    "state": "VA",
    "country": "USA",
    "tour": "Spring 1977",
    "collection": "Spring 1977",
    "tags": [
      "1977"
    ],
    "svg": "/shows/1977-05-25.svg",
    "songCount": 22
  },
  {
    "id": "1977-05-26",
    "date": "1977-05-26",
    "venue": "Baltimore Civic Center",
    "city": "Baltimore",
    "state": "MD",
    "country": "USA",
    "tour": "Spring 1977",
    "collection": "Spring 1977",
    "tags": [
      "1977"
    ],
    "svg": "/shows/1977-05-26.svg",
    "songCount": 22
  },
  {
    "id": "1977-05-28",
    "date": "1977-05-28",
    "venue": "Hartford Civic Center",
    "city": "Hartford",
    "state": "CT",
    "country": "USA",
    "tour": "Spring 1977",
    "collection": "Spring 1977",
    "tags": [
      "1977"
    ],
    "svg": "/shows/1977-05-28.svg",
    "songCount": 21
  },
  {
    "id": "1989-10-08",
    "date": "1989-10-08",
    "venue": "Hampton Coliseum",
    "city": "Hampton",
    "state": "VA",
    "country": "USA",
    "tour": "Fall 1989",
    "collection": "Formerly the Warlocks",
    "tags": [
      "1989",
      "Hampton",
      "Formerly the Warlocks"
    ],
    "svg": "/shows/1989-10-08.svg",
    "songCount": 21
  },
  {
    "id": "1989-10-09",
    "date": "1989-10-09",
    "venue": "Hampton Coliseum",
    "city": "Hampton",
    "state": "VA",
    "country": "USA",
    "tour": "Fall 1989",
    "collection": "Formerly the Warlocks",
    "tags": [
      "1989",
      "Hampton",
      "Formerly the Warlocks",
      "Dark Star"
    ],
    "svg": "/shows/1989-10-09.svg",
    "songCount": 21
  },
  {
    "id": "1989-10-11",
    "date": "1989-10-11",
    "venue": "Brendan Byrne Arena",
    "city": "East Rutherford",
    "state": "NJ",
    "country": "USA",
    "tour": "Fall 1989",
    "collection": "Fall 1989",
    "tags": [
      "1989"
    ],
    "svg": "/shows/1989-10-11.svg",
    "songCount": 20
  },
  {
    "id": "1989-10-12",
    "date": "1989-10-12",
    "venue": "Brendan Byrne Arena",
    "city": "East Rutherford",
    "state": "NJ",
    "country": "USA",
    "tour": "Fall 1989",
    "collection": "Fall 1989",
    "tags": [
      "1989"
    ],
    "svg": "/shows/1989-10-12.svg",
    "songCount": 17
  },
  {
    "id": "1989-10-14",
    "date": "1989-10-14",
    "venue": "Brendan Byrne Arena",
    "city": "East Rutherford",
    "state": "NJ",
    "country": "USA",
    "tour": "Fall 1989",
    "collection": "Fall 1989",
    "tags": [
      "1989"
    ],
    "svg": "/shows/1989-10-14.svg",
    "songCount": 18
  },
  {
    "id": "1989-10-15",
    "date": "1989-10-15",
    "venue": "Brendan Byrne Arena",
    "city": "East Rutherford",
    "state": "NJ",
    "country": "USA",
    "tour": "Fall 1989",
    "collection": "Fall 1989",
    "tags": [
      "1989"
    ],
    "svg": "/shows/1989-10-15.svg",
    "songCount": 18
  },
  {
    "id": "1989-10-16",
    "date": "1989-10-16",
    "venue": "Brendan Byrne Arena",
    "city": "East Rutherford",
    "state": "NJ",
    "country": "USA",
    "tour": "Fall 1989",
    "collection": "Fall 1989",
    "tags": [
      "1989"
    ],
    "svg": "/shows/1989-10-16.svg",
    "songCount": 20
  },
  {
    "id": "1989-10-18",
    "date": "1989-10-18",
    "venue": "Spectrum",
    "city": "Philadelphia",
    "state": "PA",
    "country": "USA",
    "tour": "Fall 1989",
    "collection": "Fall 1989",
    "tags": [
      "1989"
    ],
    "svg": "/shows/1989-10-18.svg",
    "songCount": 20
  },
  {
    "id": "1989-10-19",
    "date": "1989-10-19",
    "venue": "Spectrum",
    "city": "Philadelphia",
    "state": "PA",
    "country": "USA",
    "tour": "Fall 1989",
    "collection": "Fall 1989",
    "tags": [
      "1989"
    ],
    "svg": "/shows/1989-10-19.svg",
    "songCount": 22
  },
  {
    "id": "1989-10-20",
    "date": "1989-10-20",
    "venue": "Spectrum",
    "city": "Philadelphia",
    "state": "PA",
    "country": "USA",
    "tour": "Fall 1989",
    "collection": "Fall 1989",
    "tags": [
      "1989"
    ],
    "svg": "/shows/1989-10-20.svg",
    "songCount": 22
  },
  {
    "id": "1989-10-22",
    "date": "1989-10-22",
    "venue": "Charlotte Coliseum",
    "city": "Charlotte",
    "state": "NC",
    "country": "USA",
    "tour": "Fall 1989",
    "collection": "Fall 1989",
    "tags": [
      "1989"
    ],
    "svg": "/shows/1989-10-22.svg",
    "songCount": 21
  },
  {
    "id": "1989-10-23",
    "date": "1989-10-23",
    "venue": "Charlotte Coliseum",
    "city": "Charlotte",
    "state": "NC",
    "country": "USA",
    "tour": "Fall 1989",
    "collection": "Fall 1989",
    "tags": [
      "1989"
    ],
    "svg": "/shows/1989-10-23.svg",
    "songCount": 20
  },
  {
    "id": "1989-10-25",
    "date": "1989-10-25",
    "venue": "Miami Arena",
    "city": "Miami",
    "state": "FL",
    "country": "USA",
    "tour": "Fall 1989",
    "collection": "Fall 1989",
    "tags": [
      "1989"
    ],
    "svg": "/shows/1989-10-25.svg",
    "songCount": 19
  },
  {
    "id": "1989-10-26",
    "date": "1989-10-26",
    "venue": "Miami Arena",
    "city": "Miami",
    "state": "FL",
    "country": "USA",
    "tour": "Fall 1989",
    "collection": "Fall 1989",
    "tags": [
      "1989"
    ],
    "svg": "/shows/1989-10-26.svg",
    "songCount": 18
  },
  {
    "id": "1990-03-14",
    "date": "1990-03-14",
    "venue": "Capitol Centre",
    "city": "Landover",
    "state": "MD",
    "country": "USA",
    "tour": "Spring 1990",
    "collection": "Spring 1990",
    "tags": [
      "1990"
    ],
    "svg": "/shows/1990-03-14.svg",
    "songCount": 20
  },
  {
    "id": "1990-03-15",
    "date": "1990-03-15",
    "venue": "Capitol Centre",
    "city": "Landover",
    "state": "MD",
    "country": "USA",
    "tour": "Spring 1990",
    "collection": "Spring 1990",
    "tags": [
      "1990"
    ],
    "svg": "/shows/1990-03-15.svg",
    "songCount": 21
  },
  {
    "id": "1990-03-16",
    "date": "1990-03-16",
    "venue": "Capitol Centre",
    "city": "Landover",
    "state": "MD",
    "country": "USA",
    "tour": "Spring 1990",
    "collection": "Spring 1990",
    "tags": [
      "1990"
    ],
    "svg": "/shows/1990-03-16.svg",
    "songCount": 20
  },
  {
    "id": "1990-03-18",
    "date": "1990-03-18",
    "venue": "Hartford Civic Center",
    "city": "Hartford",
    "state": "CT",
    "country": "USA",
    "tour": "Spring 1990",
    "collection": "Spring 1990",
    "tags": [
      "1990"
    ],
    "svg": "/shows/1990-03-18.svg",
    "songCount": 21
  },
  {
    "id": "1990-03-19",
    "date": "1990-03-19",
    "venue": "Hartford Civic Center",
    "city": "Hartford",
    "state": "CT",
    "country": "USA",
    "tour": "Spring 1990",
    "collection": "Spring 1990",
    "tags": [
      "1990"
    ],
    "svg": "/shows/1990-03-19.svg",
    "songCount": 19
  },
  {
    "id": "1990-03-21",
    "date": "1990-03-21",
    "venue": "Copps Coliseum",
    "city": "Hamilton",
    "state": "ON",
    "country": "CAN",
    "tour": "Spring 1990",
    "collection": "Spring 1990",
    "tags": [
      "1990"
    ],
    "svg": "/shows/1990-03-21.svg",
    "songCount": 20
  },
  {
    "id": "1990-03-22",
    "date": "1990-03-22",
    "venue": "Copps Coliseum",
    "city": "Hamilton",
    "state": "ON",
    "country": "CAN",
    "tour": "Spring 1990",
    "collection": "Spring 1990",
    "tags": [
      "1990"
    ],
    "svg": "/shows/1990-03-22.svg",
    "songCount": 21
  },
  {
    "id": "1990-03-24",
    "date": "1990-03-24",
    "venue": "Knickerbocker Arena",
    "city": "Albany",
    "state": "NY",
    "country": "USA",
    "tour": "Spring 1990",
    "collection": "Spring 1990",
    "tags": [
      "1990"
    ],
    "svg": "/shows/1990-03-24.svg",
    "songCount": 20
  },
  {
    "id": "1990-03-25",
    "date": "1990-03-25",
    "venue": "Knickerbocker Arena",
    "city": "Albany",
    "state": "NY",
    "country": "USA",
    "tour": "Spring 1990",
    "collection": "Spring 1990",
    "tags": [
      "1990"
    ],
    "svg": "/shows/1990-03-25.svg",
    "songCount": 20
  },
  {
    "id": "1990-03-26",
    "date": "1990-03-26",
    "venue": "Knickerbocker Arena",
    "city": "Albany",
    "state": "NY",
    "country": "USA",
    "tour": "Spring 1990",
    "collection": "Spring 1990",
    "tags": [
      "1990"
    ],
    "svg": "/shows/1990-03-26.svg",
    "songCount": 20
  },
  {
    "id": "1990-03-28",
    "date": "1990-03-28",
    "venue": "Nassau Coliseum",
    "city": "Uniondale",
    "state": "NY",
    "country": "USA",
    "tour": "Spring 1990",
    "collection": "Spring 1990",
    "tags": [
      "1990"
    ],
    "svg": "/shows/1990-03-28.svg",
    "songCount": 19
  },
  {
    "id": "1990-03-29",
    "date": "1990-03-29",
    "venue": "Nassau Coliseum",
    "city": "Uniondale",
    "state": "NY",
    "country": "USA",
    "tour": "Spring 1990",
    "collection": "Spring 1990",
    "tags": [
      "1990"
    ],
    "svg": "/shows/1990-03-29.svg",
    "songCount": 17
  },
  {
    "id": "1990-03-30",
    "date": "1990-03-30",
    "venue": "Nassau Coliseum",
    "city": "Uniondale",
    "state": "NY",
    "country": "USA",
    "tour": "Spring 1990",
    "collection": "Spring 1990",
    "tags": [
      "1990"
    ],
    "svg": "/shows/1990-03-30.svg",
    "songCount": 21
  },
  {
    "id": "1990-04-01",
    "date": "1990-04-01",
    "venue": "The Omni",
    "city": "Atlanta",
    "state": "GA",
    "country": "USA",
    "tour": "Spring 1990",
    "collection": "Spring 1990",
    "tags": [
      "1990"
    ],
    "svg": "/shows/1990-04-01.svg",
    "songCount": 22
  },
  {
    "id": "1990-04-02",
    "date": "1990-04-02",
    "venue": "The Omni",
    "city": "Atlanta",
    "state": "GA",
    "country": "USA",
    "tour": "Spring 1990",
    "collection": "Spring 1990",
    "tags": [
      "1990"
    ],
    "svg": "/shows/1990-04-02.svg",
    "songCount": 18
  },
  {
    "id": "1990-04-03",
    "date": "1990-04-03",
    "venue": "The Omni",
    "city": "Atlanta",
    "state": "GA",
    "country": "USA",
    "tour": "Spring 1990",
    "collection": "Spring 1990",
    "tags": [
      "1990"
    ],
    "svg": "/shows/1990-04-03.svg",
    "songCount": 20
  },
  {
    "id": "1995-07-09",
    "date": "1995-07-09",
    "venue": "Soldier Field",
    "city": "Chicago",
    "state": "IL",
    "country": "USA",
    "tour": "Summer 1995",
    "collection": "Final Show",
    "tags": [
      "1995",
      "Final Show",
      "Soldier Field"
    ],
    "svg": "/shows/1995-07-09.svg",
    "songCount": 18
  }
];
