// GENERATED by `npm run generate` from data/shows/**/*.json — do not edit by hand.
import type { ShowSummary } from '@/wwob';

export const shows: ShowSummary[] = [
  {
    "id": "19690227",
    "date": "1969-02-27",
    "venue": "Fillmore West",
    "city": "San Francisco",
    "state": "CA",
    "country": "USA",
    "tour": "1969",
    "collection": "Fillmore West 1969",
    "tags": [
      "1969",
      "Dark Star",
      "Live/Dead"
    ],
    "svg": "/shows/19690227.svg",
    "songCount": 10,
    "durationSeconds": 7079
  },
  {
    "id": "19690228",
    "date": "1969-02-28",
    "venue": "Fillmore West",
    "city": "San Francisco",
    "state": "CA",
    "country": "USA",
    "tour": "1969",
    "collection": "Fillmore West 1969",
    "tags": [
      "1969",
      "Dark Star",
      "Live/Dead"
    ],
    "svg": "/shows/19690228.svg",
    "songCount": 16,
    "durationSeconds": 10032
  },
  {
    "id": "19690301",
    "date": "1969-03-01",
    "venue": "Fillmore West",
    "city": "San Francisco",
    "state": "CA",
    "country": "USA",
    "tour": "1969",
    "collection": "Fillmore West 1969",
    "tags": [
      "1969",
      "Dark Star",
      "Live/Dead"
    ],
    "svg": "/shows/19690301.svg",
    "songCount": 11,
    "durationSeconds": 7403
  },
  {
    "id": "19690302",
    "date": "1969-03-02",
    "venue": "Fillmore West",
    "city": "San Francisco",
    "state": "CA",
    "country": "USA",
    "tour": "1969",
    "collection": "Fillmore West 1969",
    "tags": [
      "1969",
      "Dark Star",
      "Live/Dead"
    ],
    "svg": "/shows/19690302.svg",
    "songCount": 14,
    "durationSeconds": 9923
  },
  {
    "id": "19720407",
    "date": "1972-04-07",
    "venue": "Wembley Empire Pool",
    "city": "London",
    "country": "ENG",
    "tour": "Europe 1972",
    "collection": "Europe 72",
    "tags": [
      "1972"
    ],
    "svg": "/shows/19720407.svg",
    "songCount": 25,
    "durationSeconds": 9837
  },
  {
    "id": "19720408",
    "date": "1972-04-08",
    "venue": "Wembley Empire Pool",
    "city": "London",
    "country": "ENG",
    "tour": "Europe 1972",
    "collection": "Europe 72",
    "tags": [
      "1972"
    ],
    "svg": "/shows/19720408.svg",
    "songCount": 22,
    "durationSeconds": 10716
  },
  {
    "id": "19720411",
    "date": "1972-04-11",
    "venue": "City Hall",
    "city": "Newcastle",
    "country": "ENG",
    "tour": "Europe 1972",
    "collection": "Europe 72",
    "tags": [
      "1972"
    ],
    "svg": "/shows/19720411.svg",
    "songCount": 27,
    "durationSeconds": 12168
  },
  {
    "id": "19720414",
    "date": "1972-04-14",
    "venue": "Tivoli Concert Hall",
    "city": "Copenhagen",
    "country": "DNK",
    "tour": "Europe 1972",
    "collection": "Europe 72",
    "tags": [
      "1972"
    ],
    "svg": "/shows/19720414.svg",
    "songCount": 29,
    "durationSeconds": 12421
  },
  {
    "id": "19720416",
    "date": "1972-04-16",
    "venue": "Stakladen Cafeteria, Aarhus University",
    "city": "Aarhus",
    "country": "DNK",
    "tour": "Europe 1972",
    "collection": "Europe 72",
    "tags": [
      "1972"
    ],
    "svg": "/shows/19720416.svg",
    "songCount": 26,
    "durationSeconds": 10197
  },
  {
    "id": "19720417",
    "date": "1972-04-17",
    "venue": "Tivoli Concert Hall",
    "city": "Copenhagen",
    "country": "DNK",
    "tour": "Europe 1972",
    "collection": "Europe 72",
    "tags": [
      "1972"
    ],
    "svg": "/shows/19720417.svg",
    "songCount": 23,
    "durationSeconds": 11049
  },
  {
    "id": "19720421",
    "date": "1972-04-21",
    "venue": "Beat Club",
    "city": "Bremen",
    "country": "BRD",
    "tour": "Europe 1972",
    "collection": "Europe 72",
    "tags": [
      "1972"
    ],
    "svg": "/shows/19720421.svg",
    "songCount": 10,
    "durationSeconds": 4775
  },
  {
    "id": "19720424",
    "date": "1972-04-24",
    "venue": "Rheinhalle",
    "city": "Düsseldorf",
    "country": "BRD",
    "tour": "Europe 1972",
    "collection": "Europe 72",
    "tags": [
      "1972"
    ],
    "svg": "/shows/19720424.svg",
    "songCount": 26,
    "durationSeconds": 12312
  },
  {
    "id": "19720426",
    "date": "1972-04-26",
    "venue": "Jahrhundert Halle",
    "city": "Frankfurt",
    "country": "BRD",
    "tour": "Europe 1972",
    "collection": "Europe 72",
    "tags": [
      "1972"
    ],
    "svg": "/shows/19720426.svg",
    "songCount": 30,
    "durationSeconds": 13885
  },
  {
    "id": "19720429",
    "date": "1972-04-29",
    "venue": "Musikhalle",
    "city": "Hamburg",
    "country": "BRD",
    "tour": "Europe 1972",
    "collection": "Europe 72",
    "tags": [
      "1972"
    ],
    "svg": "/shows/19720429.svg",
    "songCount": 22,
    "durationSeconds": 10631
  },
  {
    "id": "19720503",
    "date": "1972-05-03",
    "venue": "Olympia Theatre",
    "city": "Paris",
    "country": "FRA",
    "tour": "Europe 1972",
    "collection": "Europe 72",
    "tags": [
      "1972"
    ],
    "svg": "/shows/19720503.svg",
    "songCount": 32,
    "durationSeconds": 13291
  },
  {
    "id": "19720504",
    "date": "1972-05-04",
    "venue": "Olympia Theatre",
    "city": "Paris",
    "country": "FRA",
    "tour": "Europe 1972",
    "collection": "Europe 72",
    "tags": [
      "1972"
    ],
    "svg": "/shows/19720504.svg",
    "songCount": 29,
    "durationSeconds": 12856
  },
  {
    "id": "19720507",
    "date": "1972-05-07",
    "venue": "Bickershaw Festival",
    "city": "Wigan",
    "country": "ENG",
    "tour": "Europe 1972",
    "collection": "Europe 72",
    "tags": [
      "1972"
    ],
    "svg": "/shows/19720507.svg",
    "songCount": 27,
    "durationSeconds": 14348
  },
  {
    "id": "19720510",
    "date": "1972-05-10",
    "venue": "Concertgebouw",
    "city": "Amsterdam",
    "country": "HOL",
    "tour": "Europe 1972",
    "collection": "Europe 72",
    "tags": [
      "1972"
    ],
    "svg": "/shows/19720510.svg",
    "songCount": 32,
    "durationSeconds": 12983
  },
  {
    "id": "19720511",
    "date": "1972-05-11",
    "venue": "Grote Zaal De Doelen",
    "city": "Rotterdam",
    "country": "HOL",
    "tour": "Europe 1972",
    "collection": "Europe 72",
    "tags": [
      "1972"
    ],
    "svg": "/shows/19720511.svg",
    "songCount": 29,
    "durationSeconds": 13459
  },
  {
    "id": "19720513",
    "date": "1972-05-13",
    "venue": "Lille Fairgrounds",
    "city": "Lille",
    "country": "FRA",
    "tour": "Europe 1972",
    "collection": "Europe 72",
    "tags": [
      "1972"
    ],
    "svg": "/shows/19720513.svg",
    "songCount": 25,
    "durationSeconds": 10156
  },
  {
    "id": "19720516",
    "date": "1972-05-16",
    "venue": "La Grande Salle Du Grand Theatre",
    "city": "Luxembourg",
    "country": "LUX",
    "tour": "Europe 1972",
    "collection": "Europe 72",
    "tags": [
      "1972"
    ],
    "svg": "/shows/19720516.svg",
    "songCount": 22,
    "durationSeconds": 8726
  },
  {
    "id": "19720518",
    "date": "1972-05-18",
    "venue": "Kongressaal",
    "city": "Munich",
    "country": "BRD",
    "tour": "Europe 1972",
    "collection": "Europe 72",
    "tags": [
      "1972"
    ],
    "svg": "/shows/19720518.svg",
    "songCount": 25,
    "durationSeconds": 11220
  },
  {
    "id": "19720523",
    "date": "1972-05-23",
    "venue": "Lyceum Theatre",
    "city": "London",
    "country": "ENG",
    "tour": "Europe 1972",
    "collection": "Europe 72",
    "tags": [
      "1972"
    ],
    "svg": "/shows/19720523.svg",
    "songCount": 30,
    "durationSeconds": 12618
  },
  {
    "id": "19720524",
    "date": "1972-05-24",
    "venue": "Lyceum Theatre",
    "city": "London",
    "country": "ENG",
    "tour": "Europe 1972",
    "collection": "Europe 72",
    "tags": [
      "1972"
    ],
    "svg": "/shows/19720524.svg",
    "songCount": 26,
    "durationSeconds": 11352
  },
  {
    "id": "19720525",
    "date": "1972-05-25",
    "venue": "Lyceum Theatre",
    "city": "London",
    "country": "ENG",
    "tour": "Europe 1972",
    "collection": "Europe 72",
    "tags": [
      "1972"
    ],
    "svg": "/shows/19720525.svg",
    "songCount": 27,
    "durationSeconds": 12367
  },
  {
    "id": "19720526",
    "date": "1972-05-26",
    "venue": "Lyceum Theatre",
    "city": "London",
    "country": "ENG",
    "tour": "Europe 1972",
    "collection": "Europe 72",
    "tags": [
      "1972"
    ],
    "svg": "/shows/19720526.svg",
    "songCount": 31,
    "durationSeconds": 13367
  },
  {
    "id": "19720827",
    "date": "1972-08-27",
    "venue": "Old Renaissance Faire Grounds",
    "city": "Veneta",
    "state": "OR",
    "country": "USA",
    "tour": "Summer 1972",
    "collection": "Sunshine Daydream",
    "tags": [
      "1972",
      "Sunshine Daydream",
      "Dark Star"
    ],
    "svg": "/shows/19720827.svg",
    "songCount": 20,
    "durationSeconds": 10319
  },
  {
    "id": "19741016",
    "date": "1974-10-16",
    "venue": "Winterland Arena",
    "city": "San Francisco",
    "state": "CA",
    "country": "USA",
    "tour": "Fall 1974",
    "collection": "Winterland 1974",
    "tags": [
      "1974",
      "Wall of Sound",
      "Winterland"
    ],
    "svg": "/shows/19741016.svg",
    "songCount": 24,
    "durationSeconds": 14221
  },
  {
    "id": "19741017",
    "date": "1974-10-17",
    "venue": "Winterland Arena",
    "city": "San Francisco",
    "state": "CA",
    "country": "USA",
    "tour": "Fall 1974",
    "collection": "Winterland 1974",
    "tags": [
      "1974",
      "Wall of Sound",
      "Winterland"
    ],
    "svg": "/shows/19741017.svg",
    "songCount": 28,
    "durationSeconds": 11413
  },
  {
    "id": "19741018",
    "date": "1974-10-18",
    "venue": "Winterland Arena",
    "city": "San Francisco",
    "state": "CA",
    "country": "USA",
    "tour": "Fall 1974",
    "collection": "Winterland 1974",
    "tags": [
      "1974",
      "Wall of Sound",
      "Winterland"
    ],
    "svg": "/shows/19741018.svg",
    "songCount": 26,
    "durationSeconds": 11526
  },
  {
    "id": "19741019",
    "date": "1974-10-19",
    "venue": "Winterland Arena",
    "city": "San Francisco",
    "state": "CA",
    "country": "USA",
    "tour": "Fall 1974",
    "collection": "Winterland 1974",
    "tags": [
      "1974",
      "Wall of Sound",
      "Winterland"
    ],
    "svg": "/shows/19741019.svg",
    "songCount": 32,
    "durationSeconds": 12292
  },
  {
    "id": "19741020",
    "date": "1974-10-20",
    "venue": "Winterland Arena",
    "city": "San Francisco",
    "state": "CA",
    "country": "USA",
    "tour": "Fall 1974",
    "collection": "Winterland 1974",
    "tags": [
      "1974",
      "Wall of Sound",
      "Winterland"
    ],
    "svg": "/shows/19741020.svg",
    "songCount": 28,
    "durationSeconds": 13795
  },
  {
    "id": "19760603",
    "date": "1976-06-03",
    "venue": "Paramount Theatre",
    "city": "Portland",
    "state": "OR",
    "country": "USA",
    "tour": "June 1976",
    "collection": "June 1976",
    "tags": [
      "1976"
    ],
    "svg": "/shows/19760603.svg",
    "songCount": 24,
    "durationSeconds": 10320
  },
  {
    "id": "19760604",
    "date": "1976-06-04",
    "venue": "Paramount Theatre",
    "city": "Portland",
    "state": "OR",
    "country": "USA",
    "tour": "June 1976",
    "collection": "June 1976",
    "tags": [
      "1976"
    ],
    "svg": "/shows/19760604.svg",
    "songCount": 28,
    "durationSeconds": 9671
  },
  {
    "id": "19760609",
    "date": "1976-06-09",
    "venue": "Boston Music Hall",
    "city": "Boston",
    "state": "MA",
    "country": "USA",
    "tour": "June 1976",
    "collection": "June 1976",
    "tags": [
      "1976"
    ],
    "svg": "/shows/19760609.svg",
    "songCount": 23,
    "durationSeconds": 11219
  },
  {
    "id": "19760610",
    "date": "1976-06-10",
    "venue": "Boston Music Hall",
    "city": "Boston",
    "state": "MA",
    "country": "USA",
    "tour": "June 1976",
    "collection": "June 1976",
    "tags": [
      "1976"
    ],
    "svg": "/shows/19760610.svg",
    "songCount": 22,
    "durationSeconds": 9979
  },
  {
    "id": "19760611",
    "date": "1976-06-11",
    "venue": "Boston Music Hall",
    "city": "Boston",
    "state": "MA",
    "country": "USA",
    "tour": "June 1976",
    "collection": "June 1976",
    "tags": [
      "1976"
    ],
    "svg": "/shows/19760611.svg",
    "songCount": 24,
    "durationSeconds": 10382
  },
  {
    "id": "19760612",
    "date": "1976-06-12",
    "venue": "Boston Music Hall",
    "city": "Boston",
    "state": "MA",
    "country": "USA",
    "tour": "June 1976",
    "collection": "June 1976",
    "tags": [
      "1976"
    ],
    "svg": "/shows/19760612.svg",
    "songCount": 25,
    "durationSeconds": 9087
  },
  {
    "id": "19760614",
    "date": "1976-06-14",
    "venue": "Beacon Theatre",
    "city": "New York",
    "state": "NY",
    "country": "USA",
    "tour": "June 1976",
    "collection": "June 1976",
    "tags": [
      "1976"
    ],
    "svg": "/shows/19760614.svg",
    "songCount": 23,
    "durationSeconds": 10980
  },
  {
    "id": "19760615",
    "date": "1976-06-15",
    "venue": "Beacon Theatre",
    "city": "New York",
    "state": "NY",
    "country": "USA",
    "tour": "June 1976",
    "collection": "June 1976",
    "tags": [
      "1976"
    ],
    "svg": "/shows/19760615.svg",
    "songCount": 21,
    "durationSeconds": 9847
  },
  {
    "id": "19760617",
    "date": "1976-06-17",
    "venue": "Capitol Theatre",
    "city": "Passaic",
    "state": "NJ",
    "country": "USA",
    "tour": "June 1976",
    "collection": "June 1976",
    "tags": [
      "1976"
    ],
    "svg": "/shows/19760617.svg",
    "songCount": 24,
    "durationSeconds": 10475
  },
  {
    "id": "19760618",
    "date": "1976-06-18",
    "venue": "Capitol Theatre",
    "city": "Passaic",
    "state": "NJ",
    "country": "USA",
    "tour": "June 1976",
    "collection": "June 1976",
    "tags": [
      "1976"
    ],
    "svg": "/shows/19760618.svg",
    "songCount": 20,
    "durationSeconds": 8395
  },
  {
    "id": "19760619",
    "date": "1976-06-19",
    "venue": "Capitol Theatre",
    "city": "Passaic",
    "state": "NJ",
    "country": "USA",
    "tour": "June 1976",
    "collection": "June 1976",
    "tags": [
      "1976"
    ],
    "svg": "/shows/19760619.svg",
    "songCount": 20,
    "durationSeconds": 9825
  },
  {
    "id": "19760621",
    "date": "1976-06-21",
    "venue": "Tower Theatre",
    "city": "Upper Darby",
    "state": "PA",
    "country": "USA",
    "tour": "June 1976",
    "collection": "June 1976",
    "tags": [
      "1976"
    ],
    "svg": "/shows/19760621.svg",
    "songCount": 22,
    "durationSeconds": 9318
  },
  {
    "id": "19760622",
    "date": "1976-06-22",
    "venue": "Tower Theatre",
    "city": "Upper Darby",
    "state": "PA",
    "country": "USA",
    "tour": "June 1976",
    "collection": "June 1976",
    "tags": [
      "1976"
    ],
    "svg": "/shows/19760622.svg",
    "songCount": 21,
    "durationSeconds": 10701
  },
  {
    "id": "19760623",
    "date": "1976-06-23",
    "venue": "Tower Theatre",
    "city": "Upper Darby",
    "state": "PA",
    "country": "USA",
    "tour": "June 1976",
    "collection": "June 1976",
    "tags": [
      "1976"
    ],
    "svg": "/shows/19760623.svg",
    "songCount": 25,
    "durationSeconds": 8755
  },
  {
    "id": "19760624",
    "date": "1976-06-24",
    "venue": "Tower Theatre",
    "city": "Upper Darby",
    "state": "PA",
    "country": "USA",
    "tour": "June 1976",
    "collection": "June 1976",
    "tags": [
      "1976"
    ],
    "svg": "/shows/19760624.svg",
    "songCount": 18,
    "durationSeconds": 7851
  },
  {
    "id": "19760626",
    "date": "1976-06-26",
    "venue": "Auditorium Theatre",
    "city": "Chicago",
    "state": "IL",
    "country": "USA",
    "tour": "June 1976",
    "collection": "June 1976",
    "tags": [
      "1976"
    ],
    "svg": "/shows/19760626.svg",
    "songCount": 22,
    "durationSeconds": 9327
  },
  {
    "id": "19760627",
    "date": "1976-06-27",
    "venue": "Auditorium Theatre",
    "city": "Chicago",
    "state": "IL",
    "country": "USA",
    "tour": "June 1976",
    "collection": "June 1976",
    "tags": [
      "1976"
    ],
    "svg": "/shows/19760627.svg",
    "songCount": 20,
    "durationSeconds": 8212
  },
  {
    "id": "19760628",
    "date": "1976-06-28",
    "venue": "Auditorium Theatre",
    "city": "Chicago",
    "state": "IL",
    "country": "USA",
    "tour": "June 1976",
    "collection": "June 1976",
    "tags": [
      "1976"
    ],
    "svg": "/shows/19760628.svg",
    "songCount": 18,
    "durationSeconds": 7887
  },
  {
    "id": "19760629",
    "date": "1976-06-29",
    "venue": "Auditorium Theatre",
    "city": "Chicago",
    "state": "IL",
    "country": "USA",
    "tour": "June 1976",
    "collection": "June 1976",
    "tags": [
      "1976"
    ],
    "svg": "/shows/19760629.svg",
    "songCount": 22,
    "durationSeconds": 9180
  },
  {
    "id": "19770422",
    "date": "1977-04-22",
    "venue": "Spectrum",
    "city": "Philadelphia",
    "state": "PA",
    "country": "USA",
    "tour": "Spring 1977",
    "collection": "Spring 1977",
    "tags": [
      "1977"
    ],
    "svg": "/shows/19770422.svg",
    "songCount": 18,
    "durationSeconds": 8617
  },
  {
    "id": "19770423",
    "date": "1977-04-23",
    "venue": "Springfield Civic Center Arena",
    "city": "Springfield",
    "state": "MA",
    "country": "USA",
    "tour": "Spring 1977",
    "collection": "Spring 1977",
    "tags": [
      "1977"
    ],
    "svg": "/shows/19770423.svg",
    "songCount": 20,
    "durationSeconds": 8812
  },
  {
    "id": "19770425",
    "date": "1977-04-25",
    "venue": "Capitol Theatre",
    "city": "Passaic",
    "state": "NJ",
    "country": "USA",
    "tour": "Spring 1977",
    "collection": "Spring 1977",
    "tags": [
      "1977"
    ],
    "svg": "/shows/19770425.svg",
    "songCount": 21,
    "durationSeconds": 8709
  },
  {
    "id": "19770426",
    "date": "1977-04-26",
    "venue": "Capitol Theatre",
    "city": "Passaic",
    "state": "NJ",
    "country": "USA",
    "tour": "Spring 1977",
    "collection": "Spring 1977",
    "tags": [
      "1977"
    ],
    "svg": "/shows/19770426.svg",
    "songCount": 17,
    "durationSeconds": 7904
  },
  {
    "id": "19770427",
    "date": "1977-04-27",
    "venue": "Capitol Theatre",
    "city": "Passaic",
    "state": "NJ",
    "country": "USA",
    "tour": "Spring 1977",
    "collection": "Spring 1977",
    "tags": [
      "1977"
    ],
    "svg": "/shows/19770427.svg",
    "songCount": 18,
    "durationSeconds": 8245
  },
  {
    "id": "19770429",
    "date": "1977-04-29",
    "venue": "The Palladium",
    "city": "New York",
    "state": "NY",
    "country": "USA",
    "tour": "Spring 1977",
    "collection": "Spring 1977",
    "tags": [
      "1977"
    ],
    "svg": "/shows/19770429.svg",
    "songCount": 23,
    "durationSeconds": 9890
  },
  {
    "id": "19770430",
    "date": "1977-04-30",
    "venue": "The Palladium",
    "city": "New York",
    "state": "NY",
    "country": "USA",
    "tour": "Spring 1977",
    "collection": "Spring 1977",
    "tags": [
      "1977"
    ],
    "svg": "/shows/19770430.svg",
    "songCount": 21,
    "durationSeconds": 8638
  },
  {
    "id": "19770501",
    "date": "1977-05-01",
    "venue": "The Palladium",
    "city": "New York",
    "state": "NY",
    "country": "USA",
    "tour": "Spring 1977",
    "collection": "Spring 1977",
    "tags": [
      "1977"
    ],
    "svg": "/shows/19770501.svg",
    "songCount": 21,
    "durationSeconds": 8371
  },
  {
    "id": "19770503",
    "date": "1977-05-03",
    "venue": "The Palladium",
    "city": "New York",
    "state": "NY",
    "country": "USA",
    "tour": "Spring 1977",
    "collection": "Spring 1977",
    "tags": [
      "1977"
    ],
    "svg": "/shows/19770503.svg",
    "songCount": 24,
    "durationSeconds": 10294
  },
  {
    "id": "19770504",
    "date": "1977-05-04",
    "venue": "The Palladium",
    "city": "New York",
    "state": "NY",
    "country": "USA",
    "tour": "Spring 1977",
    "collection": "Spring 1977",
    "tags": [
      "1977"
    ],
    "svg": "/shows/19770504.svg",
    "songCount": 17,
    "durationSeconds": 9178
  },
  {
    "id": "19770505",
    "date": "1977-05-05",
    "venue": "Veterans Memorial Coliseum",
    "city": "New Haven",
    "state": "CT",
    "country": "USA",
    "tour": "Spring 1977",
    "collection": "Spring 1977",
    "tags": [
      "1977"
    ],
    "svg": "/shows/19770505.svg",
    "songCount": 19,
    "durationSeconds": 8483
  },
  {
    "id": "19770507",
    "date": "1977-05-07",
    "venue": "Boston Garden",
    "city": "Boston",
    "state": "MA",
    "country": "USA",
    "tour": "Spring 1977",
    "collection": "Spring 1977",
    "tags": [
      "1977",
      "Boston"
    ],
    "svg": "/shows/19770507.svg",
    "songCount": 20,
    "durationSeconds": 9303
  },
  {
    "id": "19770508",
    "date": "1977-05-08",
    "venue": "Barton Hall, Cornell University",
    "city": "Ithaca",
    "state": "NY",
    "country": "USA",
    "tour": "Spring 1977",
    "collection": "Spring 1977",
    "tags": [
      "1977",
      "Cornell",
      "Barton Hall"
    ],
    "svg": "/shows/19770508.svg",
    "songCount": 20,
    "durationSeconds": 9130
  },
  {
    "id": "19770509",
    "date": "1977-05-09",
    "venue": "War Memorial Auditorium",
    "city": "Buffalo",
    "state": "NY",
    "country": "USA",
    "tour": "Spring 1977",
    "collection": "Spring 1977",
    "tags": [
      "1977",
      "Buffalo"
    ],
    "svg": "/shows/19770509.svg",
    "songCount": 21,
    "durationSeconds": 8882
  },
  {
    "id": "19770511",
    "date": "1977-05-11",
    "venue": "St. Paul Civic Center Arena",
    "city": "St. Paul",
    "state": "MN",
    "country": "USA",
    "tour": "Spring 1977",
    "collection": "Spring 1977",
    "tags": [
      "1977"
    ],
    "svg": "/shows/19770511.svg",
    "songCount": 24,
    "durationSeconds": 10240
  },
  {
    "id": "19770512",
    "date": "1977-05-12",
    "venue": "Auditorium Theatre",
    "city": "Chicago",
    "state": "IL",
    "country": "USA",
    "tour": "Spring 1977",
    "collection": "Spring 1977",
    "tags": [
      "1977"
    ],
    "svg": "/shows/19770512.svg",
    "songCount": 21,
    "durationSeconds": 9174
  },
  {
    "id": "19770513",
    "date": "1977-05-13",
    "venue": "Auditorium Theatre",
    "city": "Chicago",
    "state": "IL",
    "country": "USA",
    "tour": "Spring 1977",
    "collection": "Spring 1977",
    "tags": [
      "1977"
    ],
    "svg": "/shows/19770513.svg",
    "songCount": 20,
    "durationSeconds": 8490
  },
  {
    "id": "19770515",
    "date": "1977-05-15",
    "venue": "St. Louis Arena",
    "city": "St. Louis",
    "state": "MO",
    "country": "USA",
    "tour": "Spring 1977",
    "collection": "Spring 1977",
    "tags": [
      "1977"
    ],
    "svg": "/shows/19770515.svg",
    "songCount": 21,
    "durationSeconds": 9059
  },
  {
    "id": "19770517",
    "date": "1977-05-17",
    "venue": "University of Alabama, Memorial Coliseum",
    "city": "Tuscaloosa",
    "state": "AL",
    "country": "USA",
    "tour": "Spring 1977",
    "collection": "Spring 1977",
    "tags": [
      "1977"
    ],
    "svg": "/shows/19770517.svg",
    "songCount": 25,
    "durationSeconds": 11443
  },
  {
    "id": "19770518",
    "date": "1977-05-18",
    "venue": "Fox Theatre",
    "city": "Atlanta",
    "state": "GA",
    "country": "USA",
    "tour": "Spring 1977",
    "collection": "Spring 1977",
    "tags": [
      "1977"
    ],
    "svg": "/shows/19770518.svg",
    "songCount": 19,
    "durationSeconds": 8840
  },
  {
    "id": "19770519",
    "date": "1977-05-19",
    "venue": "Fox Theatre",
    "city": "Atlanta",
    "state": "GA",
    "country": "USA",
    "tour": "Spring 1977",
    "collection": "Spring 1977",
    "tags": [
      "1977"
    ],
    "svg": "/shows/19770519.svg",
    "songCount": 19,
    "durationSeconds": 10220
  },
  {
    "id": "19770521",
    "date": "1977-05-21",
    "venue": "Lakeland Civic Center Arena",
    "city": "Lakeland",
    "state": "FL",
    "country": "USA",
    "tour": "Spring 1977",
    "collection": "Spring 1977",
    "tags": [
      "1977"
    ],
    "svg": "/shows/19770521.svg",
    "songCount": 24,
    "durationSeconds": 10776
  },
  {
    "id": "19770522",
    "date": "1977-05-22",
    "venue": "Sportatorium",
    "city": "Pembroke Pines",
    "state": "FL",
    "country": "USA",
    "tour": "Spring 1977",
    "collection": "Spring 1977",
    "tags": [
      "1977"
    ],
    "svg": "/shows/19770522.svg",
    "songCount": 24,
    "durationSeconds": 11189
  },
  {
    "id": "19770525",
    "date": "1977-05-25",
    "venue": "The Mosque",
    "city": "Richmond",
    "state": "VA",
    "country": "USA",
    "tour": "Spring 1977",
    "collection": "Spring 1977",
    "tags": [
      "1977"
    ],
    "svg": "/shows/19770525.svg",
    "songCount": 22,
    "durationSeconds": 9635
  },
  {
    "id": "19770526",
    "date": "1977-05-26",
    "venue": "Baltimore Civic Center",
    "city": "Baltimore",
    "state": "MD",
    "country": "USA",
    "tour": "Spring 1977",
    "collection": "Spring 1977",
    "tags": [
      "1977"
    ],
    "svg": "/shows/19770526.svg",
    "songCount": 22,
    "durationSeconds": 9692
  },
  {
    "id": "19770528",
    "date": "1977-05-28",
    "venue": "Hartford Civic Center",
    "city": "Hartford",
    "state": "CT",
    "country": "USA",
    "tour": "Spring 1977",
    "collection": "Spring 1977",
    "tags": [
      "1977"
    ],
    "svg": "/shows/19770528.svg",
    "songCount": 21,
    "durationSeconds": 10008
  },
  {
    "id": "19790107",
    "date": "1979-01-07",
    "venue": "Madison Square Garden",
    "city": "New York",
    "state": "NY",
    "country": "USA",
    "collection": "Madison Square Garden",
    "tags": [
      "1979"
    ],
    "svg": "/shows/19790107.svg",
    "songCount": 20,
    "durationSeconds": 8718
  },
  {
    "id": "19790108",
    "date": "1979-01-08",
    "venue": "Madison Square Garden",
    "city": "New York",
    "state": "NY",
    "country": "USA",
    "collection": "Madison Square Garden",
    "tags": [
      "1979"
    ],
    "svg": "/shows/19790108.svg",
    "songCount": 21,
    "durationSeconds": 10138
  },
  {
    "id": "19790904",
    "date": "1979-09-04",
    "venue": "Madison Square Garden",
    "city": "New York",
    "state": "NY",
    "country": "USA",
    "collection": "Madison Square Garden",
    "tags": [
      "1979"
    ],
    "svg": "/shows/19790904.svg",
    "songCount": 19,
    "durationSeconds": 9461
  },
  {
    "id": "19790905",
    "date": "1979-09-05",
    "venue": "Madison Square Garden",
    "city": "New York",
    "state": "NY",
    "country": "USA",
    "collection": "Madison Square Garden",
    "tags": [
      "1979"
    ],
    "svg": "/shows/19790905.svg",
    "songCount": 19,
    "durationSeconds": 9464
  },
  {
    "id": "19790906",
    "date": "1979-09-06",
    "venue": "Madison Square Garden",
    "city": "New York",
    "state": "NY",
    "country": "USA",
    "collection": "Madison Square Garden",
    "tags": [
      "1979"
    ],
    "svg": "/shows/19790906.svg",
    "songCount": 22,
    "durationSeconds": 9972
  },
  {
    "id": "19810309",
    "date": "1981-03-09",
    "venue": "Madison Square Garden",
    "city": "New York",
    "state": "NY",
    "country": "USA",
    "collection": "Madison Square Garden",
    "tags": [
      "1981"
    ],
    "svg": "/shows/19810309.svg",
    "songCount": 21,
    "durationSeconds": 10331
  },
  {
    "id": "19810310",
    "date": "1981-03-10",
    "venue": "Madison Square Garden",
    "city": "New York",
    "state": "NY",
    "country": "USA",
    "collection": "Madison Square Garden",
    "tags": [
      "1981"
    ],
    "svg": "/shows/19810310.svg",
    "songCount": 24,
    "durationSeconds": 10297
  },
  {
    "id": "19820920",
    "date": "1982-09-20",
    "venue": "Madison Square Garden",
    "city": "New York",
    "state": "NY",
    "country": "USA",
    "collection": "Madison Square Garden",
    "tags": [
      "1982"
    ],
    "svg": "/shows/19820920.svg",
    "songCount": 22,
    "durationSeconds": 10006
  },
  {
    "id": "19820921",
    "date": "1982-09-21",
    "venue": "Madison Square Garden",
    "city": "New York",
    "state": "NY",
    "country": "USA",
    "collection": "Madison Square Garden",
    "tags": [
      "1982"
    ],
    "svg": "/shows/19820921.svg",
    "songCount": 22,
    "durationSeconds": 10264
  },
  {
    "id": "19831011",
    "date": "1983-10-11",
    "venue": "Madison Square Garden",
    "city": "New York",
    "state": "NY",
    "country": "USA",
    "collection": "Madison Square Garden",
    "tags": [
      "1983"
    ],
    "svg": "/shows/19831011.svg",
    "songCount": 20,
    "durationSeconds": 8459
  },
  {
    "id": "19831012",
    "date": "1983-10-12",
    "venue": "Madison Square Garden",
    "city": "New York",
    "state": "NY",
    "country": "USA",
    "collection": "Madison Square Garden",
    "tags": [
      "1983"
    ],
    "svg": "/shows/19831012.svg",
    "songCount": 20,
    "durationSeconds": 10237
  },
  {
    "id": "19870915",
    "date": "1987-09-15",
    "venue": "Madison Square Garden",
    "city": "New York",
    "state": "NY",
    "country": "USA",
    "collection": "Madison Square Garden",
    "tags": [
      "1987"
    ],
    "svg": "/shows/19870915.svg",
    "songCount": 20,
    "durationSeconds": 7838
  },
  {
    "id": "19870916",
    "date": "1987-09-16",
    "venue": "Madison Square Garden",
    "city": "New York",
    "state": "NY",
    "country": "USA",
    "collection": "Madison Square Garden",
    "tags": [
      "1987"
    ],
    "svg": "/shows/19870916.svg",
    "songCount": 21,
    "durationSeconds": 9114
  },
  {
    "id": "19870918",
    "date": "1987-09-18",
    "venue": "Madison Square Garden",
    "city": "New York",
    "state": "NY",
    "country": "USA",
    "collection": "Madison Square Garden",
    "tags": [
      "1987"
    ],
    "svg": "/shows/19870918.svg",
    "songCount": 18,
    "durationSeconds": 7774
  },
  {
    "id": "19870919",
    "date": "1987-09-19",
    "venue": "Madison Square Garden",
    "city": "New York",
    "state": "NY",
    "country": "USA",
    "collection": "Madison Square Garden",
    "tags": [
      "1987"
    ],
    "svg": "/shows/19870919.svg",
    "songCount": 19,
    "durationSeconds": 7725
  },
  {
    "id": "19870920",
    "date": "1987-09-20",
    "venue": "Madison Square Garden",
    "city": "New York",
    "state": "NY",
    "country": "USA",
    "collection": "Madison Square Garden",
    "tags": [
      "1987"
    ],
    "svg": "/shows/19870920.svg",
    "songCount": 20,
    "durationSeconds": 8082
  },
  {
    "id": "19880914",
    "date": "1988-09-14",
    "venue": "Madison Square Garden",
    "city": "New York",
    "state": "NY",
    "country": "USA",
    "collection": "Madison Square Garden",
    "tags": [
      "1988"
    ],
    "svg": "/shows/19880914.svg",
    "songCount": 20,
    "durationSeconds": 8356
  },
  {
    "id": "19880915",
    "date": "1988-09-15",
    "venue": "Madison Square Garden",
    "city": "New York",
    "state": "NY",
    "country": "USA",
    "collection": "Madison Square Garden",
    "tags": [
      "1988"
    ],
    "svg": "/shows/19880915.svg",
    "songCount": 18,
    "durationSeconds": 7797
  },
  {
    "id": "19880916",
    "date": "1988-09-16",
    "venue": "Madison Square Garden",
    "city": "New York",
    "state": "NY",
    "country": "USA",
    "collection": "Madison Square Garden",
    "tags": [
      "1988"
    ],
    "svg": "/shows/19880916.svg",
    "songCount": 20,
    "durationSeconds": 8928
  },
  {
    "id": "19880918",
    "date": "1988-09-18",
    "venue": "Madison Square Garden",
    "city": "New York",
    "state": "NY",
    "country": "USA",
    "collection": "Madison Square Garden",
    "tags": [
      "1988"
    ],
    "svg": "/shows/19880918.svg",
    "songCount": 18,
    "durationSeconds": 8030
  },
  {
    "id": "19880919",
    "date": "1988-09-19",
    "venue": "Madison Square Garden",
    "city": "New York",
    "state": "NY",
    "country": "USA",
    "collection": "Madison Square Garden",
    "tags": [
      "1988"
    ],
    "svg": "/shows/19880919.svg",
    "songCount": 19,
    "durationSeconds": 7988
  },
  {
    "id": "19880920",
    "date": "1988-09-20",
    "venue": "Madison Square Garden",
    "city": "New York",
    "state": "NY",
    "country": "USA",
    "collection": "Madison Square Garden",
    "tags": [
      "1988"
    ],
    "svg": "/shows/19880920.svg",
    "songCount": 18,
    "durationSeconds": 8043
  },
  {
    "id": "19880922",
    "date": "1988-09-22",
    "venue": "Madison Square Garden",
    "city": "New York",
    "state": "NY",
    "country": "USA",
    "collection": "Madison Square Garden",
    "tags": [
      "1988"
    ],
    "svg": "/shows/19880922.svg",
    "songCount": 20,
    "durationSeconds": 7789
  },
  {
    "id": "19880923",
    "date": "1988-09-23",
    "venue": "Madison Square Garden",
    "city": "New York",
    "state": "NY",
    "country": "USA",
    "collection": "Madison Square Garden",
    "tags": [
      "1988"
    ],
    "svg": "/shows/19880923.svg",
    "songCount": 19,
    "durationSeconds": 8257
  },
  {
    "id": "19880924",
    "date": "1988-09-24",
    "venue": "Madison Square Garden",
    "city": "New York",
    "state": "NY",
    "country": "USA",
    "collection": "Madison Square Garden",
    "tags": [
      "1988"
    ],
    "svg": "/shows/19880924.svg",
    "songCount": 21,
    "durationSeconds": 9599
  },
  {
    "id": "19891008",
    "date": "1989-10-08",
    "venue": "Hampton Coliseum",
    "city": "Hampton",
    "state": "VA",
    "country": "USA",
    "tour": "Fall 1989",
    "collection": "Formerly the Warlocks",
    "tags": [
      "1989",
      "Hampton",
      "Formerly the Warlocks"
    ],
    "svg": "/shows/19891008.svg",
    "songCount": 21,
    "durationSeconds": 9047
  },
  {
    "id": "19891009",
    "date": "1989-10-09",
    "venue": "Hampton Coliseum",
    "city": "Hampton",
    "state": "VA",
    "country": "USA",
    "tour": "Fall 1989",
    "collection": "Formerly the Warlocks",
    "tags": [
      "1989",
      "Hampton",
      "Formerly the Warlocks",
      "Dark Star"
    ],
    "svg": "/shows/19891009.svg",
    "songCount": 21,
    "durationSeconds": 10619
  },
  {
    "id": "19891011",
    "date": "1989-10-11",
    "venue": "Brendan Byrne Arena",
    "city": "East Rutherford",
    "state": "NJ",
    "country": "USA",
    "tour": "Fall 1989",
    "collection": "Fall 1989",
    "tags": [
      "1989"
    ],
    "svg": "/shows/19891011.svg",
    "songCount": 20,
    "durationSeconds": 9064
  },
  {
    "id": "19891012",
    "date": "1989-10-12",
    "venue": "Brendan Byrne Arena",
    "city": "East Rutherford",
    "state": "NJ",
    "country": "USA",
    "tour": "Fall 1989",
    "collection": "Fall 1989",
    "tags": [
      "1989"
    ],
    "svg": "/shows/19891012.svg",
    "songCount": 17,
    "durationSeconds": 8525
  },
  {
    "id": "19891014",
    "date": "1989-10-14",
    "venue": "Brendan Byrne Arena",
    "city": "East Rutherford",
    "state": "NJ",
    "country": "USA",
    "tour": "Fall 1989",
    "collection": "Fall 1989",
    "tags": [
      "1989"
    ],
    "svg": "/shows/19891014.svg",
    "songCount": 18,
    "durationSeconds": 7837
  },
  {
    "id": "19891015",
    "date": "1989-10-15",
    "venue": "Brendan Byrne Arena",
    "city": "East Rutherford",
    "state": "NJ",
    "country": "USA",
    "tour": "Fall 1989",
    "collection": "Fall 1989",
    "tags": [
      "1989"
    ],
    "svg": "/shows/19891015.svg",
    "songCount": 18,
    "durationSeconds": 8278
  },
  {
    "id": "19891016",
    "date": "1989-10-16",
    "venue": "Brendan Byrne Arena",
    "city": "East Rutherford",
    "state": "NJ",
    "country": "USA",
    "tour": "Fall 1989",
    "collection": "Fall 1989",
    "tags": [
      "1989"
    ],
    "svg": "/shows/19891016.svg",
    "songCount": 20,
    "durationSeconds": 8267
  },
  {
    "id": "19891018",
    "date": "1989-10-18",
    "venue": "Spectrum",
    "city": "Philadelphia",
    "state": "PA",
    "country": "USA",
    "tour": "Fall 1989",
    "collection": "Fall 1989",
    "tags": [
      "1989"
    ],
    "svg": "/shows/19891018.svg",
    "songCount": 20,
    "durationSeconds": 8977
  },
  {
    "id": "19891019",
    "date": "1989-10-19",
    "venue": "Spectrum",
    "city": "Philadelphia",
    "state": "PA",
    "country": "USA",
    "tour": "Fall 1989",
    "collection": "Fall 1989",
    "tags": [
      "1989"
    ],
    "svg": "/shows/19891019.svg",
    "songCount": 22,
    "durationSeconds": 8742
  },
  {
    "id": "19891020",
    "date": "1989-10-20",
    "venue": "Spectrum",
    "city": "Philadelphia",
    "state": "PA",
    "country": "USA",
    "tour": "Fall 1989",
    "collection": "Fall 1989",
    "tags": [
      "1989"
    ],
    "svg": "/shows/19891020.svg",
    "songCount": 22,
    "durationSeconds": 10489
  },
  {
    "id": "19891022",
    "date": "1989-10-22",
    "venue": "Charlotte Coliseum",
    "city": "Charlotte",
    "state": "NC",
    "country": "USA",
    "tour": "Fall 1989",
    "collection": "Fall 1989",
    "tags": [
      "1989"
    ],
    "svg": "/shows/19891022.svg",
    "songCount": 21,
    "durationSeconds": 8961
  },
  {
    "id": "19891023",
    "date": "1989-10-23",
    "venue": "Charlotte Coliseum",
    "city": "Charlotte",
    "state": "NC",
    "country": "USA",
    "tour": "Fall 1989",
    "collection": "Fall 1989",
    "tags": [
      "1989"
    ],
    "svg": "/shows/19891023.svg",
    "songCount": 20,
    "durationSeconds": 8903
  },
  {
    "id": "19891025",
    "date": "1989-10-25",
    "venue": "Miami Arena",
    "city": "Miami",
    "state": "FL",
    "country": "USA",
    "tour": "Fall 1989",
    "collection": "Fall 1989",
    "tags": [
      "1989"
    ],
    "svg": "/shows/19891025.svg",
    "songCount": 19,
    "durationSeconds": 9269
  },
  {
    "id": "19891026",
    "date": "1989-10-26",
    "venue": "Miami Arena",
    "city": "Miami",
    "state": "FL",
    "country": "USA",
    "tour": "Fall 1989",
    "collection": "Fall 1989",
    "tags": [
      "1989"
    ],
    "svg": "/shows/19891026.svg",
    "songCount": 18,
    "durationSeconds": 8645
  },
  {
    "id": "19900314",
    "date": "1990-03-14",
    "venue": "Capitol Centre",
    "city": "Landover",
    "state": "MD",
    "country": "USA",
    "tour": "Spring 1990",
    "collection": "Spring 1990",
    "tags": [
      "1990"
    ],
    "svg": "/shows/19900314.svg",
    "songCount": 20,
    "durationSeconds": 8699
  },
  {
    "id": "19900315",
    "date": "1990-03-15",
    "venue": "Capitol Centre",
    "city": "Landover",
    "state": "MD",
    "country": "USA",
    "tour": "Spring 1990",
    "collection": "Spring 1990",
    "tags": [
      "1990"
    ],
    "svg": "/shows/19900315.svg",
    "songCount": 21,
    "durationSeconds": 10031
  },
  {
    "id": "19900316",
    "date": "1990-03-16",
    "venue": "Capitol Centre",
    "city": "Landover",
    "state": "MD",
    "country": "USA",
    "tour": "Spring 1990",
    "collection": "Spring 1990",
    "tags": [
      "1990"
    ],
    "svg": "/shows/19900316.svg",
    "songCount": 20,
    "durationSeconds": 9837
  },
  {
    "id": "19900318",
    "date": "1990-03-18",
    "venue": "Hartford Civic Center",
    "city": "Hartford",
    "state": "CT",
    "country": "USA",
    "tour": "Spring 1990",
    "collection": "Spring 1990",
    "tags": [
      "1990"
    ],
    "svg": "/shows/19900318.svg",
    "songCount": 21,
    "durationSeconds": 9662
  },
  {
    "id": "19900319",
    "date": "1990-03-19",
    "venue": "Hartford Civic Center",
    "city": "Hartford",
    "state": "CT",
    "country": "USA",
    "tour": "Spring 1990",
    "collection": "Spring 1990",
    "tags": [
      "1990"
    ],
    "svg": "/shows/19900319.svg",
    "songCount": 19,
    "durationSeconds": 8846
  },
  {
    "id": "19900321",
    "date": "1990-03-21",
    "venue": "Copps Coliseum",
    "city": "Hamilton",
    "state": "ON",
    "country": "CAN",
    "tour": "Spring 1990",
    "collection": "Spring 1990",
    "tags": [
      "1990"
    ],
    "svg": "/shows/19900321.svg",
    "songCount": 20,
    "durationSeconds": 9255
  },
  {
    "id": "19900322",
    "date": "1990-03-22",
    "venue": "Copps Coliseum",
    "city": "Hamilton",
    "state": "ON",
    "country": "CAN",
    "tour": "Spring 1990",
    "collection": "Spring 1990",
    "tags": [
      "1990"
    ],
    "svg": "/shows/19900322.svg",
    "songCount": 21,
    "durationSeconds": 8931
  },
  {
    "id": "19900324",
    "date": "1990-03-24",
    "venue": "Knickerbocker Arena",
    "city": "Albany",
    "state": "NY",
    "country": "USA",
    "tour": "Spring 1990",
    "collection": "Spring 1990",
    "tags": [
      "1990"
    ],
    "svg": "/shows/19900324.svg",
    "songCount": 20,
    "durationSeconds": 9161
  },
  {
    "id": "19900325",
    "date": "1990-03-25",
    "venue": "Knickerbocker Arena",
    "city": "Albany",
    "state": "NY",
    "country": "USA",
    "tour": "Spring 1990",
    "collection": "Spring 1990",
    "tags": [
      "1990"
    ],
    "svg": "/shows/19900325.svg",
    "songCount": 20,
    "durationSeconds": 9224
  },
  {
    "id": "19900326",
    "date": "1990-03-26",
    "venue": "Knickerbocker Arena",
    "city": "Albany",
    "state": "NY",
    "country": "USA",
    "tour": "Spring 1990",
    "collection": "Spring 1990",
    "tags": [
      "1990"
    ],
    "svg": "/shows/19900326.svg",
    "songCount": 20,
    "durationSeconds": 8630
  },
  {
    "id": "19900328",
    "date": "1990-03-28",
    "venue": "Nassau Coliseum",
    "city": "Uniondale",
    "state": "NY",
    "country": "USA",
    "tour": "Spring 1990",
    "collection": "Spring 1990",
    "tags": [
      "1990"
    ],
    "svg": "/shows/19900328.svg",
    "songCount": 19,
    "durationSeconds": 8469
  },
  {
    "id": "19900329",
    "date": "1990-03-29",
    "venue": "Nassau Coliseum",
    "city": "Uniondale",
    "state": "NY",
    "country": "USA",
    "tour": "Spring 1990",
    "collection": "Spring 1990",
    "tags": [
      "1990"
    ],
    "svg": "/shows/19900329.svg",
    "songCount": 17,
    "durationSeconds": 9113
  },
  {
    "id": "19900330",
    "date": "1990-03-30",
    "venue": "Nassau Coliseum",
    "city": "Uniondale",
    "state": "NY",
    "country": "USA",
    "tour": "Spring 1990",
    "collection": "Spring 1990",
    "tags": [
      "1990"
    ],
    "svg": "/shows/19900330.svg",
    "songCount": 21,
    "durationSeconds": 9151
  },
  {
    "id": "19900401",
    "date": "1990-04-01",
    "venue": "The Omni",
    "city": "Atlanta",
    "state": "GA",
    "country": "USA",
    "tour": "Spring 1990",
    "collection": "Spring 1990",
    "tags": [
      "1990"
    ],
    "svg": "/shows/19900401.svg",
    "songCount": 22,
    "durationSeconds": 9521
  },
  {
    "id": "19900402",
    "date": "1990-04-02",
    "venue": "The Omni",
    "city": "Atlanta",
    "state": "GA",
    "country": "USA",
    "tour": "Spring 1990",
    "collection": "Spring 1990",
    "tags": [
      "1990"
    ],
    "svg": "/shows/19900402.svg",
    "songCount": 18,
    "durationSeconds": 8207
  },
  {
    "id": "19900403",
    "date": "1990-04-03",
    "venue": "The Omni",
    "city": "Atlanta",
    "state": "GA",
    "country": "USA",
    "tour": "Spring 1990",
    "collection": "Spring 1990",
    "tags": [
      "1990"
    ],
    "svg": "/shows/19900403.svg",
    "songCount": 20,
    "durationSeconds": 9469
  },
  {
    "id": "19900716",
    "date": "1990-07-16",
    "venue": "Rich Stadium",
    "city": "Buffalo",
    "state": "NY",
    "country": "USA",
    "collection": "Shows I Attended",
    "tags": [
      "1990"
    ],
    "svg": "/shows/19900716.svg",
    "songCount": 24,
    "durationSeconds": 10628
  },
  {
    "id": "19900914",
    "date": "1990-09-14",
    "venue": "Madison Square Garden",
    "city": "New York",
    "state": "NY",
    "country": "USA",
    "collection": "Madison Square Garden",
    "tags": [
      "1990"
    ],
    "svg": "/shows/19900914.svg",
    "songCount": 19,
    "durationSeconds": 10331
  },
  {
    "id": "19900915",
    "date": "1990-09-15",
    "venue": "Madison Square Garden",
    "city": "New York",
    "state": "NY",
    "country": "USA",
    "collection": "Madison Square Garden",
    "tags": [
      "1990"
    ],
    "svg": "/shows/19900915.svg",
    "songCount": 21,
    "durationSeconds": 9908
  },
  {
    "id": "19900916",
    "date": "1990-09-16",
    "venue": "Madison Square Garden",
    "city": "New York",
    "state": "NY",
    "country": "USA",
    "collection": "Madison Square Garden",
    "tags": [
      "1990"
    ],
    "svg": "/shows/19900916.svg",
    "songCount": 20,
    "durationSeconds": 10781
  },
  {
    "id": "19900918",
    "date": "1990-09-18",
    "venue": "Madison Square Garden",
    "city": "New York",
    "state": "NY",
    "country": "USA",
    "collection": "Madison Square Garden",
    "tags": [
      "1990"
    ],
    "svg": "/shows/19900918.svg",
    "songCount": 18,
    "durationSeconds": 10967
  },
  {
    "id": "19900919",
    "date": "1990-09-19",
    "venue": "Madison Square Garden",
    "city": "New York",
    "state": "NY",
    "country": "USA",
    "collection": "Madison Square Garden",
    "tags": [
      "1990"
    ],
    "svg": "/shows/19900919.svg",
    "songCount": 21,
    "durationSeconds": 10592
  },
  {
    "id": "19900920",
    "date": "1990-09-20",
    "venue": "Madison Square Garden",
    "city": "New York",
    "state": "NY",
    "country": "USA",
    "collection": "Madison Square Garden",
    "tags": [
      "1990"
    ],
    "svg": "/shows/19900920.svg",
    "songCount": 20,
    "durationSeconds": 10264
  },
  {
    "id": "19901013",
    "date": "1990-10-13",
    "venue": "Johanneshov Isstadion",
    "city": "Stockholm",
    "country": "SWE",
    "tour": "Europe 1990",
    "collection": "Europe 1990",
    "tags": [
      "1990"
    ],
    "svg": "/shows/19901013.svg",
    "songCount": 19,
    "durationSeconds": 8479
  },
  {
    "id": "19901017",
    "date": "1990-10-17",
    "venue": "Grugahalle",
    "city": "Essen",
    "country": "DEU",
    "tour": "Europe 1990",
    "collection": "Europe 1990",
    "tags": [
      "1990"
    ],
    "svg": "/shows/19901017.svg",
    "songCount": 21,
    "durationSeconds": 8429
  },
  {
    "id": "19901019",
    "date": "1990-10-19",
    "venue": "Internationales Congress Centrum",
    "city": "Berlin",
    "country": "DEU",
    "tour": "Europe 1990",
    "collection": "Europe 1990",
    "tags": [
      "1990"
    ],
    "svg": "/shows/19901019.svg",
    "songCount": 20,
    "durationSeconds": 9710
  },
  {
    "id": "19901020",
    "date": "1990-10-20",
    "venue": "Internationales Congress Centrum",
    "city": "Berlin",
    "country": "DEU",
    "tour": "Europe 1990",
    "collection": "Europe 1990",
    "tags": [
      "1990"
    ],
    "svg": "/shows/19901020.svg",
    "songCount": 21,
    "durationSeconds": 8651
  },
  {
    "id": "19901022",
    "date": "1990-10-22",
    "venue": "Festhalle",
    "city": "Frankfurt",
    "country": "DEU",
    "tour": "Europe 1990",
    "collection": "Europe 1990",
    "tags": [
      "1990"
    ],
    "svg": "/shows/19901022.svg",
    "songCount": 19,
    "durationSeconds": 8320
  },
  {
    "id": "19901024",
    "date": "1990-10-24",
    "venue": "Sporthalle",
    "city": "Hamburg",
    "country": "DEU",
    "tour": "Europe 1990",
    "collection": "Europe 1990",
    "tags": [
      "1990"
    ],
    "svg": "/shows/19901024.svg",
    "songCount": 21,
    "durationSeconds": 8767
  },
  {
    "id": "19901027",
    "date": "1990-10-27",
    "venue": "Zénith Paris",
    "city": "Paris",
    "country": "FRA",
    "tour": "Europe 1990",
    "collection": "Europe 1990",
    "tags": [
      "1990"
    ],
    "svg": "/shows/19901027.svg",
    "songCount": 21,
    "durationSeconds": 9984
  },
  {
    "id": "19901028",
    "date": "1990-10-28",
    "venue": "Zénith Paris",
    "city": "Paris",
    "country": "FRA",
    "tour": "Europe 1990",
    "collection": "Europe 1990",
    "tags": [
      "1990"
    ],
    "svg": "/shows/19901028.svg",
    "songCount": 20,
    "durationSeconds": 9644
  },
  {
    "id": "19901030",
    "date": "1990-10-30",
    "venue": "Wembley Arena",
    "city": "London",
    "country": "ENG",
    "tour": "Europe 1990",
    "collection": "Europe 1990",
    "tags": [
      "1990"
    ],
    "svg": "/shows/19901030.svg",
    "songCount": 20,
    "durationSeconds": 9051
  },
  {
    "id": "19901031",
    "date": "1990-10-31",
    "venue": "Wembley Arena",
    "city": "London",
    "country": "ENG",
    "tour": "Europe 1990",
    "collection": "Europe 1990",
    "tags": [
      "1990"
    ],
    "svg": "/shows/19901031.svg",
    "songCount": 22,
    "durationSeconds": 11233
  },
  {
    "id": "19901101",
    "date": "1990-11-01",
    "venue": "Wembley Arena",
    "city": "London",
    "country": "ENG",
    "tour": "Europe 1990",
    "collection": "Europe 1990",
    "tags": [
      "1990"
    ],
    "svg": "/shows/19901101.svg",
    "songCount": 20,
    "durationSeconds": 9567
  },
  {
    "id": "19910908",
    "date": "1991-09-08",
    "venue": "Madison Square Garden",
    "city": "New York",
    "state": "NY",
    "country": "USA",
    "collection": "Madison Square Garden",
    "tags": [
      "1991"
    ],
    "svg": "/shows/19910908.svg",
    "songCount": 19,
    "durationSeconds": 10016
  },
  {
    "id": "19910909",
    "date": "1991-09-09",
    "venue": "Madison Square Garden",
    "city": "New York",
    "state": "NY",
    "country": "USA",
    "collection": "Madison Square Garden",
    "tags": [
      "1991"
    ],
    "svg": "/shows/19910909.svg",
    "songCount": 18,
    "durationSeconds": 9045
  },
  {
    "id": "19910910",
    "date": "1991-09-10",
    "venue": "Madison Square Garden",
    "city": "New York",
    "state": "NY",
    "country": "USA",
    "collection": "Madison Square Garden",
    "tags": [
      "1991"
    ],
    "svg": "/shows/19910910.svg",
    "songCount": 19,
    "durationSeconds": 9737
  },
  {
    "id": "19910912",
    "date": "1991-09-12",
    "venue": "Madison Square Garden",
    "city": "New York",
    "state": "NY",
    "country": "USA",
    "collection": "Madison Square Garden",
    "tags": [
      "1991"
    ],
    "svg": "/shows/19910912.svg",
    "songCount": 20,
    "durationSeconds": 9539
  },
  {
    "id": "19910913",
    "date": "1991-09-13",
    "venue": "Madison Square Garden",
    "city": "New York",
    "state": "NY",
    "country": "USA",
    "collection": "Madison Square Garden",
    "tags": [
      "1991"
    ],
    "svg": "/shows/19910913.svg",
    "songCount": 18,
    "durationSeconds": 10387
  },
  {
    "id": "19910914",
    "date": "1991-09-14",
    "venue": "Madison Square Garden",
    "city": "New York",
    "state": "NY",
    "country": "USA",
    "collection": "Madison Square Garden",
    "tags": [
      "1991"
    ],
    "svg": "/shows/19910914.svg",
    "songCount": 19,
    "durationSeconds": 8520
  },
  {
    "id": "19910916",
    "date": "1991-09-16",
    "venue": "Madison Square Garden",
    "city": "New York",
    "state": "NY",
    "country": "USA",
    "collection": "Madison Square Garden",
    "tags": [
      "1991"
    ],
    "svg": "/shows/19910916.svg",
    "songCount": 19,
    "durationSeconds": 9486
  },
  {
    "id": "19910917",
    "date": "1991-09-17",
    "venue": "Madison Square Garden",
    "city": "New York",
    "state": "NY",
    "country": "USA",
    "collection": "Madison Square Garden",
    "tags": [
      "1991"
    ],
    "svg": "/shows/19910917.svg",
    "songCount": 19,
    "durationSeconds": 9627
  },
  {
    "id": "19910918",
    "date": "1991-09-18",
    "venue": "Madison Square Garden",
    "city": "New York",
    "state": "NY",
    "country": "USA",
    "collection": "Madison Square Garden",
    "tags": [
      "1991"
    ],
    "svg": "/shows/19910918.svg",
    "songCount": 18,
    "durationSeconds": 9358
  },
  {
    "id": "19920606",
    "date": "1992-06-06",
    "venue": "Rich Stadium",
    "city": "Buffalo",
    "state": "NY",
    "country": "USA",
    "collection": "Shows I Attended",
    "tags": [
      "1992"
    ],
    "svg": "/shows/19920606.svg",
    "songCount": 20,
    "durationSeconds": 9290
  },
  {
    "id": "19930606",
    "date": "1993-06-06",
    "venue": "Giants Stadium",
    "city": "East Rutherford",
    "state": "NJ",
    "country": "USA",
    "collection": "Shows I Attended",
    "tags": [
      "1993"
    ],
    "svg": "/shows/19930606.svg",
    "songCount": 18,
    "durationSeconds": 9271
  },
  {
    "id": "19930613",
    "date": "1993-06-13",
    "venue": "Rich Stadium",
    "city": "Buffalo",
    "state": "NY",
    "country": "USA",
    "collection": "Shows I Attended",
    "tags": [
      "1993"
    ],
    "svg": "/shows/19930613.svg",
    "songCount": 19,
    "durationSeconds": 8671
  },
  {
    "id": "19930916",
    "date": "1993-09-16",
    "venue": "Madison Square Garden",
    "city": "New York",
    "state": "NY",
    "country": "USA",
    "collection": "Madison Square Garden",
    "tags": [
      "1993"
    ],
    "svg": "/shows/19930916.svg",
    "songCount": 19,
    "durationSeconds": 9574
  },
  {
    "id": "19930917",
    "date": "1993-09-17",
    "venue": "Madison Square Garden",
    "city": "New York",
    "state": "NY",
    "country": "USA",
    "collection": "Madison Square Garden",
    "tags": [
      "1993"
    ],
    "svg": "/shows/19930917.svg",
    "songCount": 19,
    "durationSeconds": 9944
  },
  {
    "id": "19930918",
    "date": "1993-09-18",
    "venue": "Madison Square Garden",
    "city": "New York",
    "state": "NY",
    "country": "USA",
    "collection": "Madison Square Garden",
    "tags": [
      "1993"
    ],
    "svg": "/shows/19930918.svg",
    "songCount": 18,
    "durationSeconds": 9209
  },
  {
    "id": "19930920",
    "date": "1993-09-20",
    "venue": "Madison Square Garden",
    "city": "New York",
    "state": "NY",
    "country": "USA",
    "collection": "Madison Square Garden",
    "tags": [
      "1993"
    ],
    "svg": "/shows/19930920.svg",
    "songCount": 19,
    "durationSeconds": 9082
  },
  {
    "id": "19930921",
    "date": "1993-09-21",
    "venue": "Madison Square Garden",
    "city": "New York",
    "state": "NY",
    "country": "USA",
    "collection": "Madison Square Garden",
    "tags": [
      "1993"
    ],
    "svg": "/shows/19930921.svg",
    "songCount": 18,
    "durationSeconds": 8922
  },
  {
    "id": "19930922",
    "date": "1993-09-22",
    "venue": "Madison Square Garden",
    "city": "New York",
    "state": "NY",
    "country": "USA",
    "collection": "Madison Square Garden",
    "tags": [
      "1993"
    ],
    "svg": "/shows/19930922.svg",
    "songCount": 17,
    "durationSeconds": 8917
  },
  {
    "id": "19941013",
    "date": "1994-10-13",
    "venue": "Madison Square Garden",
    "city": "New York",
    "state": "NY",
    "country": "USA",
    "collection": "Madison Square Garden",
    "tags": [
      "1994"
    ],
    "svg": "/shows/19941013.svg",
    "songCount": 19,
    "durationSeconds": 10128
  },
  {
    "id": "19941014",
    "date": "1994-10-14",
    "venue": "Madison Square Garden",
    "city": "New York",
    "state": "NY",
    "country": "USA",
    "collection": "Madison Square Garden",
    "tags": [
      "1994"
    ],
    "svg": "/shows/19941014.svg",
    "songCount": 19,
    "durationSeconds": 9989
  },
  {
    "id": "19941015",
    "date": "1994-10-15",
    "venue": "Madison Square Garden",
    "city": "New York",
    "state": "NY",
    "country": "USA",
    "collection": "Madison Square Garden",
    "tags": [
      "1994"
    ],
    "svg": "/shows/19941015.svg",
    "songCount": 18,
    "durationSeconds": 9175
  },
  {
    "id": "19941017",
    "date": "1994-10-17",
    "venue": "Madison Square Garden",
    "city": "New York",
    "state": "NY",
    "country": "USA",
    "collection": "Madison Square Garden",
    "tags": [
      "1994"
    ],
    "svg": "/shows/19941017.svg",
    "songCount": 17,
    "durationSeconds": 9941
  },
  {
    "id": "19941018",
    "date": "1994-10-18",
    "venue": "Madison Square Garden",
    "city": "New York",
    "state": "NY",
    "country": "USA",
    "collection": "Madison Square Garden",
    "tags": [
      "1994"
    ],
    "svg": "/shows/19941018.svg",
    "songCount": 19,
    "durationSeconds": 9453
  },
  {
    "id": "19941019",
    "date": "1994-10-19",
    "venue": "Madison Square Garden",
    "city": "New York",
    "state": "NY",
    "country": "USA",
    "collection": "Madison Square Garden",
    "tags": [
      "1994"
    ],
    "svg": "/shows/19941019.svg",
    "songCount": 17,
    "durationSeconds": 9643
  },
  {
    "id": "19950709",
    "date": "1995-07-09",
    "venue": "Soldier Field",
    "city": "Chicago",
    "state": "IL",
    "country": "USA",
    "tour": "Summer 1995",
    "collection": "Final Show",
    "tags": [
      "1995",
      "Final Show",
      "Soldier Field"
    ],
    "svg": "/shows/19950709.svg",
    "songCount": 18,
    "durationSeconds": 9106
  }
];
