// GENERATED by `npm run generate` from data/shows/*.json — do not edit by hand.
import type { ManifestEntry } from '@/wwob';

export const shows: ManifestEntry[] = [
  {
    "id": "1972-08-27",
    "date": "1972-08-27",
    "venue": "Old Renaissance Faire Grounds",
    "city": "Veneta",
    "state": "OR",
    "country": "USA",
    "tour": "Summer 1972",
    "collection": "Sunshine Daydream",
    "tags": [
      "1972",
      "Sunshine Daydream",
      "Dark Star"
    ],
    "svg": "/shows/1972-08-27.svg",
    "songCount": 20,
    "songs": [
      {
        "title": "Promised Land",
        "durationSeconds": 204
      },
      {
        "title": "Sugaree",
        "durationSeconds": 450
      },
      {
        "title": "Me and My Uncle",
        "durationSeconds": 196
      },
      {
        "title": "Deal",
        "durationSeconds": 295
      },
      {
        "title": "Black-Throated Wind",
        "durationSeconds": 421
      },
      {
        "title": "China Cat Sunflower",
        "durationSeconds": 478
      },
      {
        "title": "I Know You Rider",
        "durationSeconds": 423
      },
      {
        "title": "Mexicali Blues",
        "durationSeconds": 229
      },
      {
        "title": "Bertha",
        "durationSeconds": 359
      },
      {
        "title": "Playing in the Band",
        "durationSeconds": 1197
      },
      {
        "title": "He's Gone",
        "durationSeconds": 572
      },
      {
        "title": "Jack Straw",
        "durationSeconds": 306
      },
      {
        "title": "Bird Song",
        "durationSeconds": 797
      },
      {
        "title": "Greatest Story Ever Told",
        "durationSeconds": 336
      },
      {
        "title": "Dark Star",
        "durationSeconds": 1888
      },
      {
        "title": "El Paso",
        "durationSeconds": 304
      },
      {
        "title": "Sing Me Back Home",
        "durationSeconds": 651
      },
      {
        "title": "Sugar Magnolia",
        "durationSeconds": 525
      },
      {
        "title": "Casey Jones",
        "durationSeconds": 385
      },
      {
        "title": "One More Saturday Night",
        "durationSeconds": 303
      }
    ]
  }
];
